packageName: hindsight_client_api
projectName: hindsight-client
packageVersion: 0.0.7
library: asyncio
generateSourceCodeOnly: true
# Don't generate auto tests or docs - we have our own
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
modelNameMappings:
  TagGroup-Input: MentalModelTriggerInputTagGroupsInner
  TagGroup-Output: MentalModelTriggerOutputTagGroupsInner
  TagGroupAnd_Input_and_inner: MentalModelTriggerInputTagGroupsInner
  TagGroupAnd_Output_and_inner: MentalModelTriggerOutputTagGroupsInner
