# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BankRestoreResponse(BaseModel):
    """
    Response model for restoring a whole-bank backup archive.
    """ # noqa: E501
    bank_id: StrictStr
    documents_imported: Optional[StrictInt] = 0
    facts_imported: Optional[StrictInt] = 0
    observations_imported: Optional[StrictInt] = 0
    mental_models_imported: Optional[StrictInt] = 0
    mental_model_history_imported: Optional[StrictInt] = 0
    directives_imported: Optional[StrictInt] = 0
    webhooks_imported: Optional[StrictInt] = 0
    history_rows_imported: Optional[StrictInt] = 0
    status: Optional[StrictStr] = 'restored'
    __properties: ClassVar[List[str]] = ["bank_id", "documents_imported", "facts_imported", "observations_imported", "mental_models_imported", "mental_model_history_imported", "directives_imported", "webhooks_imported", "history_rows_imported", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankRestoreResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankRestoreResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bank_id": obj.get("bank_id"),
            "documents_imported": obj.get("documents_imported") if obj.get("documents_imported") is not None else 0,
            "facts_imported": obj.get("facts_imported") if obj.get("facts_imported") is not None else 0,
            "observations_imported": obj.get("observations_imported") if obj.get("observations_imported") is not None else 0,
            "mental_models_imported": obj.get("mental_models_imported") if obj.get("mental_models_imported") is not None else 0,
            "mental_model_history_imported": obj.get("mental_model_history_imported") if obj.get("mental_model_history_imported") is not None else 0,
            "directives_imported": obj.get("directives_imported") if obj.get("directives_imported") is not None else 0,
            "webhooks_imported": obj.get("webhooks_imported") if obj.get("webhooks_imported") is not None else 0,
            "history_rows_imported": obj.get("history_rows_imported") if obj.get("history_rows_imported") is not None else 0,
            "status": obj.get("status") if obj.get("status") is not None else 'restored'
        })
        return _obj


