# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.8.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.mental_model_trigger_input_tag_groups_inner import MentalModelTriggerInputTagGroupsInner
from typing import Optional, Set
from typing_extensions import Self

class ConsolidationRequest(BaseModel):
    """
    Request model for consolidation trigger endpoint.
    """ # noqa: E501
    observation_scopes: Optional[List[List[StrictStr]]] = None
    tags: Optional[List[StrictStr]] = None
    tags_match: Optional[StrictStr] = Field(default='any', description="How to match source-fact tags: 'any', 'all', 'any_strict', 'all_strict', or 'exact'. With 'exact' and no tags (or []), only untagged source facts match.")
    tag_groups: Optional[List[MentalModelTriggerInputTagGroupsInner]] = None
    __properties: ClassVar[List[str]] = ["observation_scopes", "tags", "tags_match", "tag_groups"]

    @field_validator('tags_match')
    def tags_match_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['any', 'all', 'any_strict', 'all_strict', 'exact']):
            raise ValueError("must be one of enum values ('any', 'all', 'any_strict', 'all_strict', 'exact')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConsolidationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tag_groups (list)
        _items = []
        if self.tag_groups:
            for _item_tag_groups in self.tag_groups:
                if _item_tag_groups:
                    _items.append(_item_tag_groups.to_dict())
            _dict['tag_groups'] = _items
        # set to None if observation_scopes (nullable) is None
        # and model_fields_set contains the field
        if self.observation_scopes is None and "observation_scopes" in self.model_fields_set:
            _dict['observation_scopes'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if tag_groups (nullable) is None
        # and model_fields_set contains the field
        if self.tag_groups is None and "tag_groups" in self.model_fields_set:
            _dict['tag_groups'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConsolidationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "observation_scopes": obj.get("observation_scopes"),
            "tags": obj.get("tags"),
            "tags_match": obj.get("tags_match") if obj.get("tags_match") is not None else 'any',
            "tag_groups": [MentalModelTriggerInputTagGroupsInner.from_dict(_item) for _item in obj["tag_groups"]] if obj.get("tag_groups") is not None else None
        })
        return _obj


