# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.8.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GraphitiEdgeInvalidatedRequest(BaseModel):
    """
    C4 channel-B backflow body.  Posted by the Graphiti overlay (or any external service) when an upstream edge is invalidated. The engine resolves the source_uri back to a local memory, re-consolidates the affected observations, and optionally stamps a B1 supersession row.
    """ # noqa: E501
    edge_uuid: StrictStr = Field(description="The Graphiti edge UUID that was invalidated upstream.")
    source_uri: StrictStr = Field(description="Marker the C1 forwarder writes into EdgePayload.attributes.source_uri: 'hindsight://bank/{bank_id}/memory/{memory_id}'. Cross-bank or malformed URIs return 404 (not 5xx) per deep-dive 4 §1.3.")
    invalid_at: datetime = Field(description="When the upstream edge was invalidated. Used as the B1 valid_until value when graphiti_backflow_supersession is on (subject to the chk_mu_valid_until_after_start CHECK constraint).")
    superseded_by_fact: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["edge_uuid", "source_uri", "invalid_at", "superseded_by_fact"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GraphitiEdgeInvalidatedRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if superseded_by_fact (nullable) is None
        # and model_fields_set contains the field
        if self.superseded_by_fact is None and "superseded_by_fact" in self.model_fields_set:
            _dict['superseded_by_fact'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GraphitiEdgeInvalidatedRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "edge_uuid": obj.get("edge_uuid"),
            "source_uri": obj.get("source_uri"),
            "invalid_at": obj.get("invalid_at"),
            "superseded_by_fact": obj.get("superseded_by_fact")
        })
        return _obj


