# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.8.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.image_asset_descriptor import ImageAssetDescriptor
from typing import Optional, Set
from typing_extensions import Self

class ImageRetainAccepted(BaseModel):
    """
    ImageRetainAccepted
    """ # noqa: E501
    operation_id: StrictStr
    document_id: StrictStr
    status: Optional[StrictStr] = 'pending'
    image_assets: List[ImageAssetDescriptor]
    __properties: ClassVar[List[str]] = ["operation_id", "document_id", "status", "image_assets"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending']):
            raise ValueError("must be one of enum values ('pending')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImageRetainAccepted from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in image_assets (list)
        _items = []
        if self.image_assets:
            for _item_image_assets in self.image_assets:
                if _item_image_assets:
                    _items.append(_item_image_assets.to_dict())
            _dict['image_assets'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImageRetainAccepted from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation_id": obj.get("operation_id"),
            "document_id": obj.get("document_id"),
            "status": obj.get("status") if obj.get("status") is not None else 'pending',
            "image_assets": [ImageAssetDescriptor.from_dict(_item) for _item in obj["image_assets"]] if obj.get("image_assets") is not None else None
        })
        return _obj
