# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.8.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ImageAssetStatus(str, Enum):
    """
    Named separately so generated SDKs do not merge it with operation status.
    """

    """
    allowed enum values
    """
    READY = 'ready'
    FAILED = 'failed'
    DELETING = 'deleting'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ImageAssetStatus from a JSON string"""
        return cls(json.loads(json_str))


