# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TagGroupEntityLeaf(BaseModel):
    """
    A leaf ENTITY filter: matches memories by the entities they mention.  Tags describe which *compartment* a memory lives in; entities describe what it is *about*. On a bank whose tag vocabulary is a handful of broad topics, a tag scope cannot isolate a subject — measured on a production bank (2026-08-08), the best tag scope for one subject reached 25% precision against a 15.5% base rate, while the entity association reached 94.2% precision / 86.2% recall on the same corpus. This leaf makes that association usable anywhere a ``TagGroup`` already is: mental-model refresh scope, the staleness gate, and retrieval filtering, through the same recursive grammar.  ``entities`` are canonical names, matched case-insensitively — the same normalisation the entity registry itself enforces via its ``(bank_id, LOWER(canonical_name))`` uniqueness.  Association is inheritance-aware: a memory matches if it links the entity directly (``unit_entities``) or through any of its ``source_memory_ids`` — the lane observations use, since consolidation-produced observations carry no direct postings by design (their entity association is transitive through their sources; see ``memories/pg/graph.py:_entity_rows_for_units_sql``).  ``match=\"any\"``: mentions at least one listed entity. ``match=\"all\"``: mentions every listed entity (directly or via sources, per entity).  Constraints, enforced by ``validate_entity_leaf_placement`` at the API edge: an entity leaf may not appear under ``not`` — the two permissive fallbacks (the Python-side post-filter and the non-memory_units surfaces that strip entity leaves) evaluate an unknown entity constraint as \"matches\", and a NOT over a permissive \"matches\" silently inverts into \"exclude everything\".
    """ # noqa: E501
    entities: Annotated[List[StrictStr], Field(min_length=1)]
    match: Optional[StrictStr] = 'any'
    __properties: ClassVar[List[str]] = ["entities", "match"]

    @field_validator('match')
    def match_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['any', 'all']):
            raise ValueError("must be one of enum values ('any', 'all')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TagGroupEntityLeaf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TagGroupEntityLeaf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "entities": obj.get("entities"),
            "match": obj.get("match") if obj.get("match") is not None else 'any'
        })
        return _obj


