# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from hindsight_client_api.models.consolidation_completed_webhook_event import ConsolidationCompletedWebhookEvent
from hindsight_client_api.models.memory_defense_triggered_webhook_event import MemoryDefenseTriggeredWebhookEvent
from hindsight_client_api.models.retain_completed_webhook_event import RetainCompletedWebhookEvent
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

WEBHOOKEVENT_ONE_OF_SCHEMAS = ["ConsolidationCompletedWebhookEvent", "MemoryDefenseTriggeredWebhookEvent", "RetainCompletedWebhookEvent"]

class WebhookEvent(BaseModel):
    """
    WebhookEvent
    """
    # data type: ConsolidationCompletedWebhookEvent
    oneof_schema_1_validator: Optional[ConsolidationCompletedWebhookEvent] = None
    # data type: RetainCompletedWebhookEvent
    oneof_schema_2_validator: Optional[RetainCompletedWebhookEvent] = None
    # data type: MemoryDefenseTriggeredWebhookEvent
    oneof_schema_3_validator: Optional[MemoryDefenseTriggeredWebhookEvent] = None
    actual_instance: Optional[Union[ConsolidationCompletedWebhookEvent, MemoryDefenseTriggeredWebhookEvent, RetainCompletedWebhookEvent]] = None
    one_of_schemas: Set[str] = { "ConsolidationCompletedWebhookEvent", "MemoryDefenseTriggeredWebhookEvent", "RetainCompletedWebhookEvent" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = WebhookEvent.model_construct()
        error_messages = []
        match = 0
        # validate data type: ConsolidationCompletedWebhookEvent
        if not isinstance(v, ConsolidationCompletedWebhookEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConsolidationCompletedWebhookEvent`")
        else:
            match += 1
        # validate data type: RetainCompletedWebhookEvent
        if not isinstance(v, RetainCompletedWebhookEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RetainCompletedWebhookEvent`")
        else:
            match += 1
        # validate data type: MemoryDefenseTriggeredWebhookEvent
        if not isinstance(v, MemoryDefenseTriggeredWebhookEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MemoryDefenseTriggeredWebhookEvent`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in WebhookEvent with oneOf schemas: ConsolidationCompletedWebhookEvent, MemoryDefenseTriggeredWebhookEvent, RetainCompletedWebhookEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in WebhookEvent with oneOf schemas: ConsolidationCompletedWebhookEvent, MemoryDefenseTriggeredWebhookEvent, RetainCompletedWebhookEvent. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ConsolidationCompletedWebhookEvent
        try:
            instance.actual_instance = ConsolidationCompletedWebhookEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RetainCompletedWebhookEvent
        try:
            instance.actual_instance = RetainCompletedWebhookEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MemoryDefenseTriggeredWebhookEvent
        try:
            instance.actual_instance = MemoryDefenseTriggeredWebhookEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into WebhookEvent with oneOf schemas: ConsolidationCompletedWebhookEvent, MemoryDefenseTriggeredWebhookEvent, RetainCompletedWebhookEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into WebhookEvent with oneOf schemas: ConsolidationCompletedWebhookEvent, MemoryDefenseTriggeredWebhookEvent, RetainCompletedWebhookEvent. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ConsolidationCompletedWebhookEvent, MemoryDefenseTriggeredWebhookEvent, RetainCompletedWebhookEvent]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


