---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hindsight-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - hindsight.vectorize.io
  resources:
  - hindsightbanks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hindsight.vectorize.io
  resources:
  - hindsightbanks/status
  verbs:
  - get
  - patch
  - update
