"""
Pydantic models for mental models.
"""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class MentalModelType(str, Enum):
    """Type of mental model - what it represents."""

    ENTITY = "entity"  # Represents a person, organization, system, etc.
    CONCEPT = "concept"  # Represents an abstract idea, process, or pattern
    EVENT = "event"  # Represents a specific occurrence or series of occurrences


class MentalModelSubtype(str, Enum):
    """Subtype of mental model - how it was created."""

    STRUCTURAL = "structural"  # Derived from goal, created upfront
    EMERGENT = "emergent"  # Discovered from data patterns


class MentalModel(BaseModel):
    """
    A mental model representing synthesized understanding.

    Mental models are the agent's consolidated knowledge about entities,
    concepts, or events. Unlike raw facts, mental models provide:
    - A one-liner description for quick scanning/retrieval
    - A full summary for deep understanding
    - Triggers for keyword-based matching
    - Links to related mental models
    """

    id: str = Field(description="Unique identifier within the bank")
    bank_id: str = Field(description="Bank this mental model belongs to")
    type: MentalModelType = Field(description="What this model represents")
    subtype: MentalModelSubtype = Field(description="How this model was created")
    name: str = Field(description="Human-readable name")
    description: str = Field(description="One-liner for quick scanning and retrieval matching")
    summary: str | None = Field(default=None, description="Full synthesized understanding")

    # References
    entity_id: str | None = Field(default=None, description="Reference to entities table when type=entity")
    source_facts: list[str] = Field(default_factory=list, description="Fact IDs used to generate summary")
    triggers: list[str] = Field(default_factory=list, description="Keywords for retrieval matching")
    links: list[str] = Field(default_factory=list, description="Related mental model IDs")

    # Tags for scoped visibility (similar to document tags)
    tags: list[str] = Field(default_factory=list, description="Tags for scoped visibility filtering")

    # Timestamps
    last_updated: datetime | None = Field(default=None, description="When summary was last regenerated")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="When this model was created")


class StructuralModelTemplate(BaseModel):
    """
    A template for a structural mental model.

    Generated by LLM based on the bank's goal. Represents what any agent
    with this role would need to track.
    """

    id: str = Field(description="Identifier for this template (e.g., 'team-structure')")
    type: MentalModelType = Field(description="Type of mental model")
    name: str = Field(description="Human-readable name")
    description: str = Field(description="What this model should track")
    initial_probes: list[str] = Field(default_factory=list, description="Initial search queries to populate this model")


class StructuralModelDerivationResponse(BaseModel):
    """Response from LLM for structural model derivation."""

    templates: list[StructuralModelTemplate] = Field(description="Structural model templates derived from the goal")


class EmergentCandidate(BaseModel):
    """
    A candidate for promotion to emergent mental model.

    Detected through pattern analysis of facts.
    """

    name: str = Field(description="Name of the detected pattern/entity")
    type: MentalModelType = Field(description="Suggested type")
    detection_method: str = Field(description="How this candidate was detected")
    mention_count: int = Field(default=0, description="How many times referenced")
    entity_id: str | None = Field(default=None, description="Entity ID if detected as entity")
    relevance_score: float = Field(default=0.0, description="Score from goal filter (0-1)")


class ResearchResult(BaseModel):
    """
    Result from the research endpoint.

    Contains the answer along with the mental models and facts used.
    """

    answer: str = Field(description="The synthesized answer")
    mental_models_used: list[str] = Field(default_factory=list, description="IDs of mental models that contributed")
    facts_used: list[str] = Field(default_factory=list, description="Fact IDs that contributed")
    question_type: str | None = Field(default=None, description="Detected question type (WHO, WHAT, HOW, etc.)")
