/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ConsolidationCompletedWebhookEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsolidationCompletedWebhookEvent{}

// ConsolidationCompletedWebhookEvent struct for ConsolidationCompletedWebhookEvent
type ConsolidationCompletedWebhookEvent struct {
	Event string `json:"event"`
	BankId string `json:"bank_id"`
	OperationId string `json:"operation_id"`
	Status string `json:"status"`
	Timestamp time.Time `json:"timestamp"`
	Data ConsolidationEventData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _ConsolidationCompletedWebhookEvent ConsolidationCompletedWebhookEvent

// NewConsolidationCompletedWebhookEvent instantiates a new ConsolidationCompletedWebhookEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsolidationCompletedWebhookEvent(event string, bankId string, operationId string, status string, timestamp time.Time, data ConsolidationEventData) *ConsolidationCompletedWebhookEvent {
	this := ConsolidationCompletedWebhookEvent{}
	this.Event = event
	this.BankId = bankId
	this.OperationId = operationId
	this.Status = status
	this.Timestamp = timestamp
	this.Data = data
	return &this
}

// NewConsolidationCompletedWebhookEventWithDefaults instantiates a new ConsolidationCompletedWebhookEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsolidationCompletedWebhookEventWithDefaults() *ConsolidationCompletedWebhookEvent {
	this := ConsolidationCompletedWebhookEvent{}
	return &this
}

// GetEvent returns the Event field value
func (o *ConsolidationCompletedWebhookEvent) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *ConsolidationCompletedWebhookEvent) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *ConsolidationCompletedWebhookEvent) SetEvent(v string) {
	o.Event = v
}

// GetBankId returns the BankId field value
func (o *ConsolidationCompletedWebhookEvent) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *ConsolidationCompletedWebhookEvent) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *ConsolidationCompletedWebhookEvent) SetBankId(v string) {
	o.BankId = v
}

// GetOperationId returns the OperationId field value
func (o *ConsolidationCompletedWebhookEvent) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *ConsolidationCompletedWebhookEvent) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *ConsolidationCompletedWebhookEvent) SetOperationId(v string) {
	o.OperationId = v
}

// GetStatus returns the Status field value
func (o *ConsolidationCompletedWebhookEvent) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ConsolidationCompletedWebhookEvent) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ConsolidationCompletedWebhookEvent) SetStatus(v string) {
	o.Status = v
}

// GetTimestamp returns the Timestamp field value
func (o *ConsolidationCompletedWebhookEvent) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *ConsolidationCompletedWebhookEvent) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *ConsolidationCompletedWebhookEvent) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetData returns the Data field value
func (o *ConsolidationCompletedWebhookEvent) GetData() ConsolidationEventData {
	if o == nil {
		var ret ConsolidationEventData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ConsolidationCompletedWebhookEvent) GetDataOk() (*ConsolidationEventData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ConsolidationCompletedWebhookEvent) SetData(v ConsolidationEventData) {
	o.Data = v
}

func (o ConsolidationCompletedWebhookEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsolidationCompletedWebhookEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["bank_id"] = o.BankId
	toSerialize["operation_id"] = o.OperationId
	toSerialize["status"] = o.Status
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConsolidationCompletedWebhookEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"bank_id",
		"operation_id",
		"status",
		"timestamp",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsolidationCompletedWebhookEvent := _ConsolidationCompletedWebhookEvent{}

	err = json.Unmarshal(data, &varConsolidationCompletedWebhookEvent)

	if err != nil {
		return err
	}

	*o = ConsolidationCompletedWebhookEvent(varConsolidationCompletedWebhookEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		delete(additionalProperties, "bank_id")
		delete(additionalProperties, "operation_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConsolidationCompletedWebhookEvent struct {
	value *ConsolidationCompletedWebhookEvent
	isSet bool
}

func (v NullableConsolidationCompletedWebhookEvent) Get() *ConsolidationCompletedWebhookEvent {
	return v.value
}

func (v *NullableConsolidationCompletedWebhookEvent) Set(val *ConsolidationCompletedWebhookEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableConsolidationCompletedWebhookEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableConsolidationCompletedWebhookEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsolidationCompletedWebhookEvent(val *ConsolidationCompletedWebhookEvent) *NullableConsolidationCompletedWebhookEvent {
	return &NullableConsolidationCompletedWebhookEvent{value: val, isSet: true}
}

func (v NullableConsolidationCompletedWebhookEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsolidationCompletedWebhookEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


