/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImageAssetList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageAssetList{}

// ImageAssetList struct for ImageAssetList
type ImageAssetList struct {
	Items []ImageAssetDescriptor `json:"items"`
	Total int32 `json:"total"`
	Limit int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type _ImageAssetList ImageAssetList

// NewImageAssetList instantiates a new ImageAssetList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageAssetList(items []ImageAssetDescriptor, total int32, limit int32, offset int32) *ImageAssetList {
	this := ImageAssetList{}
	this.Items = items
	this.Total = total
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewImageAssetListWithDefaults instantiates a new ImageAssetList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageAssetListWithDefaults() *ImageAssetList {
	this := ImageAssetList{}
	return &this
}

// GetItems returns the Items field value
func (o *ImageAssetList) GetItems() []ImageAssetDescriptor {
	if o == nil {
		var ret []ImageAssetDescriptor
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ImageAssetList) GetItemsOk() ([]ImageAssetDescriptor, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ImageAssetList) SetItems(v []ImageAssetDescriptor) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *ImageAssetList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ImageAssetList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ImageAssetList) SetTotal(v int32) {
	o.Total = v
}

// GetLimit returns the Limit field value
func (o *ImageAssetList) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *ImageAssetList) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *ImageAssetList) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *ImageAssetList) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *ImageAssetList) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *ImageAssetList) SetOffset(v int32) {
	o.Offset = v
}

func (o ImageAssetList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageAssetList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	return toSerialize, nil
}

func (o *ImageAssetList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"total",
		"limit",
		"offset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageAssetList := _ImageAssetList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageAssetList)

	if err != nil {
		return err
	}

	*o = ImageAssetList(varImageAssetList)

	return err
}

type NullableImageAssetList struct {
	value *ImageAssetList
	isSet bool
}

func (v NullableImageAssetList) Get() *ImageAssetList {
	return v.value
}

func (v *NullableImageAssetList) Set(val *ImageAssetList) {
	v.value = val
	v.isSet = true
}

func (v NullableImageAssetList) IsSet() bool {
	return v.isSet
}

func (v *NullableImageAssetList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageAssetList(val *ImageAssetList) *NullableImageAssetList {
	return &NullableImageAssetList{value: val, isSet: true}
}

func (v NullableImageAssetList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageAssetList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


