/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChildOperationStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChildOperationStatus{}

// ChildOperationStatus Status of a child operation (for batch operations).
type ChildOperationStatus struct {
	OperationId string `json:"operation_id"`
	Status string `json:"status"`
	SubBatchIndex NullableInt32 `json:"sub_batch_index,omitempty"`
	ItemsCount NullableInt32 `json:"items_count,omitempty"`
	DocumentId NullableString `json:"document_id,omitempty"`
	ParentOperationId NullableString `json:"parent_operation_id,omitempty"`
	ParserName NullableString `json:"parser_name,omitempty"`
	ParserContractVersion NullableString `json:"parser_contract_version,omitempty"`
	SourceSha256 NullableString `json:"source_sha256,omitempty"`
	ErrorMessage NullableString `json:"error_message,omitempty"`
}

type _ChildOperationStatus ChildOperationStatus

// NewChildOperationStatus instantiates a new ChildOperationStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChildOperationStatus(operationId string, status string) *ChildOperationStatus {
	this := ChildOperationStatus{}
	this.OperationId = operationId
	this.Status = status
	return &this
}

// NewChildOperationStatusWithDefaults instantiates a new ChildOperationStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChildOperationStatusWithDefaults() *ChildOperationStatus {
	this := ChildOperationStatus{}
	return &this
}

// GetOperationId returns the OperationId field value
func (o *ChildOperationStatus) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *ChildOperationStatus) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *ChildOperationStatus) SetOperationId(v string) {
	o.OperationId = v
}

// GetStatus returns the Status field value
func (o *ChildOperationStatus) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ChildOperationStatus) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ChildOperationStatus) SetStatus(v string) {
	o.Status = v
}

// GetSubBatchIndex returns the SubBatchIndex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChildOperationStatus) GetSubBatchIndex() int32 {
	if o == nil || IsNil(o.SubBatchIndex.Get()) {
		var ret int32
		return ret
	}
	return *o.SubBatchIndex.Get()
}

// GetSubBatchIndexOk returns a tuple with the SubBatchIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChildOperationStatus) GetSubBatchIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubBatchIndex.Get(), o.SubBatchIndex.IsSet()
}

// HasSubBatchIndex returns a boolean if a field has been set.
func (o *ChildOperationStatus) HasSubBatchIndex() bool {
	if o != nil && o.SubBatchIndex.IsSet() {
		return true
	}

	return false
}

// SetSubBatchIndex gets a reference to the given NullableInt32 and assigns it to the SubBatchIndex field.
func (o *ChildOperationStatus) SetSubBatchIndex(v int32) {
	o.SubBatchIndex.Set(&v)
}
// SetSubBatchIndexNil sets the value for SubBatchIndex to be an explicit nil
func (o *ChildOperationStatus) SetSubBatchIndexNil() {
	o.SubBatchIndex.Set(nil)
}

// UnsetSubBatchIndex ensures that no value is present for SubBatchIndex, not even an explicit nil
func (o *ChildOperationStatus) UnsetSubBatchIndex() {
	o.SubBatchIndex.Unset()
}

// GetItemsCount returns the ItemsCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChildOperationStatus) GetItemsCount() int32 {
	if o == nil || IsNil(o.ItemsCount.Get()) {
		var ret int32
		return ret
	}
	return *o.ItemsCount.Get()
}

// GetItemsCountOk returns a tuple with the ItemsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChildOperationStatus) GetItemsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemsCount.Get(), o.ItemsCount.IsSet()
}

// HasItemsCount returns a boolean if a field has been set.
func (o *ChildOperationStatus) HasItemsCount() bool {
	if o != nil && o.ItemsCount.IsSet() {
		return true
	}

	return false
}

// SetItemsCount gets a reference to the given NullableInt32 and assigns it to the ItemsCount field.
func (o *ChildOperationStatus) SetItemsCount(v int32) {
	o.ItemsCount.Set(&v)
}
// SetItemsCountNil sets the value for ItemsCount to be an explicit nil
func (o *ChildOperationStatus) SetItemsCountNil() {
	o.ItemsCount.Set(nil)
}

// UnsetItemsCount ensures that no value is present for ItemsCount, not even an explicit nil
func (o *ChildOperationStatus) UnsetItemsCount() {
	o.ItemsCount.Unset()
}

// GetDocumentId returns the DocumentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChildOperationStatus) GetDocumentId() string {
	if o == nil || IsNil(o.DocumentId.Get()) {
		var ret string
		return ret
	}
	return *o.DocumentId.Get()
}

// GetDocumentIdOk returns a tuple with the DocumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChildOperationStatus) GetDocumentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocumentId.Get(), o.DocumentId.IsSet()
}

// HasDocumentId returns a boolean if a field has been set.
func (o *ChildOperationStatus) HasDocumentId() bool {
	if o != nil && o.DocumentId.IsSet() {
		return true
	}

	return false
}

// SetDocumentId gets a reference to the given NullableString and assigns it to the DocumentId field.
func (o *ChildOperationStatus) SetDocumentId(v string) {
	o.DocumentId.Set(&v)
}
// SetDocumentIdNil sets the value for DocumentId to be an explicit nil
func (o *ChildOperationStatus) SetDocumentIdNil() {
	o.DocumentId.Set(nil)
}

// UnsetDocumentId ensures that no value is present for DocumentId, not even an explicit nil
func (o *ChildOperationStatus) UnsetDocumentId() {
	o.DocumentId.Unset()
}

// GetParentOperationId returns the ParentOperationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChildOperationStatus) GetParentOperationId() string {
	if o == nil || IsNil(o.ParentOperationId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentOperationId.Get()
}

// GetParentOperationIdOk returns a tuple with the ParentOperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChildOperationStatus) GetParentOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentOperationId.Get(), o.ParentOperationId.IsSet()
}

// HasParentOperationId returns a boolean if a field has been set.
func (o *ChildOperationStatus) HasParentOperationId() bool {
	if o != nil && o.ParentOperationId.IsSet() {
		return true
	}

	return false
}

// SetParentOperationId gets a reference to the given NullableString and assigns it to the ParentOperationId field.
func (o *ChildOperationStatus) SetParentOperationId(v string) {
	o.ParentOperationId.Set(&v)
}
// SetParentOperationIdNil sets the value for ParentOperationId to be an explicit nil
func (o *ChildOperationStatus) SetParentOperationIdNil() {
	o.ParentOperationId.Set(nil)
}

// UnsetParentOperationId ensures that no value is present for ParentOperationId, not even an explicit nil
func (o *ChildOperationStatus) UnsetParentOperationId() {
	o.ParentOperationId.Unset()
}

// GetParserName returns the ParserName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChildOperationStatus) GetParserName() string {
	if o == nil || IsNil(o.ParserName.Get()) {
		var ret string
		return ret
	}
	return *o.ParserName.Get()
}

// GetParserNameOk returns a tuple with the ParserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChildOperationStatus) GetParserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParserName.Get(), o.ParserName.IsSet()
}

// HasParserName returns a boolean if a field has been set.
func (o *ChildOperationStatus) HasParserName() bool {
	if o != nil && o.ParserName.IsSet() {
		return true
	}

	return false
}

// SetParserName gets a reference to the given NullableString and assigns it to the ParserName field.
func (o *ChildOperationStatus) SetParserName(v string) {
	o.ParserName.Set(&v)
}
// SetParserNameNil sets the value for ParserName to be an explicit nil
func (o *ChildOperationStatus) SetParserNameNil() {
	o.ParserName.Set(nil)
}

// UnsetParserName ensures that no value is present for ParserName, not even an explicit nil
func (o *ChildOperationStatus) UnsetParserName() {
	o.ParserName.Unset()
}

// GetParserContractVersion returns the ParserContractVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChildOperationStatus) GetParserContractVersion() string {
	if o == nil || IsNil(o.ParserContractVersion.Get()) {
		var ret string
		return ret
	}
	return *o.ParserContractVersion.Get()
}

// GetParserContractVersionOk returns a tuple with the ParserContractVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChildOperationStatus) GetParserContractVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParserContractVersion.Get(), o.ParserContractVersion.IsSet()
}

// HasParserContractVersion returns a boolean if a field has been set.
func (o *ChildOperationStatus) HasParserContractVersion() bool {
	if o != nil && o.ParserContractVersion.IsSet() {
		return true
	}

	return false
}

// SetParserContractVersion gets a reference to the given NullableString and assigns it to the ParserContractVersion field.
func (o *ChildOperationStatus) SetParserContractVersion(v string) {
	o.ParserContractVersion.Set(&v)
}
// SetParserContractVersionNil sets the value for ParserContractVersion to be an explicit nil
func (o *ChildOperationStatus) SetParserContractVersionNil() {
	o.ParserContractVersion.Set(nil)
}

// UnsetParserContractVersion ensures that no value is present for ParserContractVersion, not even an explicit nil
func (o *ChildOperationStatus) UnsetParserContractVersion() {
	o.ParserContractVersion.Unset()
}

// GetSourceSha256 returns the SourceSha256 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChildOperationStatus) GetSourceSha256() string {
	if o == nil || IsNil(o.SourceSha256.Get()) {
		var ret string
		return ret
	}
	return *o.SourceSha256.Get()
}

// GetSourceSha256Ok returns a tuple with the SourceSha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChildOperationStatus) GetSourceSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceSha256.Get(), o.SourceSha256.IsSet()
}

// HasSourceSha256 returns a boolean if a field has been set.
func (o *ChildOperationStatus) HasSourceSha256() bool {
	if o != nil && o.SourceSha256.IsSet() {
		return true
	}

	return false
}

// SetSourceSha256 gets a reference to the given NullableString and assigns it to the SourceSha256 field.
func (o *ChildOperationStatus) SetSourceSha256(v string) {
	o.SourceSha256.Set(&v)
}
// SetSourceSha256Nil sets the value for SourceSha256 to be an explicit nil
func (o *ChildOperationStatus) SetSourceSha256Nil() {
	o.SourceSha256.Set(nil)
}

// UnsetSourceSha256 ensures that no value is present for SourceSha256, not even an explicit nil
func (o *ChildOperationStatus) UnsetSourceSha256() {
	o.SourceSha256.Unset()
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChildOperationStatus) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChildOperationStatus) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ChildOperationStatus) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage.IsSet() {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given NullableString and assigns it to the ErrorMessage field.
func (o *ChildOperationStatus) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}
// SetErrorMessageNil sets the value for ErrorMessage to be an explicit nil
func (o *ChildOperationStatus) SetErrorMessageNil() {
	o.ErrorMessage.Set(nil)
}

// UnsetErrorMessage ensures that no value is present for ErrorMessage, not even an explicit nil
func (o *ChildOperationStatus) UnsetErrorMessage() {
	o.ErrorMessage.Unset()
}

func (o ChildOperationStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChildOperationStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operation_id"] = o.OperationId
	toSerialize["status"] = o.Status
	if o.SubBatchIndex.IsSet() {
		toSerialize["sub_batch_index"] = o.SubBatchIndex.Get()
	}
	if o.ItemsCount.IsSet() {
		toSerialize["items_count"] = o.ItemsCount.Get()
	}
	if o.DocumentId.IsSet() {
		toSerialize["document_id"] = o.DocumentId.Get()
	}
	if o.ParentOperationId.IsSet() {
		toSerialize["parent_operation_id"] = o.ParentOperationId.Get()
	}
	if o.ParserName.IsSet() {
		toSerialize["parser_name"] = o.ParserName.Get()
	}
	if o.ParserContractVersion.IsSet() {
		toSerialize["parser_contract_version"] = o.ParserContractVersion.Get()
	}
	if o.SourceSha256.IsSet() {
		toSerialize["source_sha256"] = o.SourceSha256.Get()
	}
	if o.ErrorMessage.IsSet() {
		toSerialize["error_message"] = o.ErrorMessage.Get()
	}
	return toSerialize, nil
}

func (o *ChildOperationStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operation_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChildOperationStatus := _ChildOperationStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChildOperationStatus)

	if err != nil {
		return err
	}

	*o = ChildOperationStatus(varChildOperationStatus)

	return err
}

type NullableChildOperationStatus struct {
	value *ChildOperationStatus
	isSet bool
}

func (v NullableChildOperationStatus) Get() *ChildOperationStatus {
	return v.value
}

func (v *NullableChildOperationStatus) Set(val *ChildOperationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableChildOperationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableChildOperationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChildOperationStatus(val *ChildOperationStatus) *NullableChildOperationStatus {
	return &NullableChildOperationStatus{value: val, isSet: true}
}

func (v NullableChildOperationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChildOperationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


