/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the RetainEventData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetainEventData{}

// RetainEventData struct for RetainEventData
type RetainEventData struct {
	DocumentId *string `json:"document_id,omitempty"`
	Tags []string `json:"tags,omitempty"`
	// Memory units the document owns after this retain (the same number the Documents API reports). 0 means fact extraction returned nothing, so the document is stored but unreachable through recall/reflect until it is reprocessed. Null when the retain carried no document_id, since there is then no document to count against.
	MemoryUnitCount *int32 `json:"memory_unit_count,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RetainEventData RetainEventData

// NewRetainEventData instantiates a new RetainEventData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetainEventData() *RetainEventData {
	this := RetainEventData{}
	return &this
}

// NewRetainEventDataWithDefaults instantiates a new RetainEventData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetainEventDataWithDefaults() *RetainEventData {
	this := RetainEventData{}
	return &this
}

// GetDocumentId returns the DocumentId field value if set, zero value otherwise.
func (o *RetainEventData) GetDocumentId() string {
	if o == nil || IsNil(o.DocumentId) {
		var ret string
		return ret
	}
	return *o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetainEventData) GetDocumentIdOk() (*string, bool) {
	if o == nil || IsNil(o.DocumentId) {
		return nil, false
	}
	return o.DocumentId, true
}

// HasDocumentId returns a boolean if a field has been set.
func (o *RetainEventData) HasDocumentId() bool {
	if o != nil && !IsNil(o.DocumentId) {
		return true
	}

	return false
}

// SetDocumentId gets a reference to the given string and assigns it to the DocumentId field.
func (o *RetainEventData) SetDocumentId(v string) {
	o.DocumentId = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *RetainEventData) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetainEventData) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *RetainEventData) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *RetainEventData) SetTags(v []string) {
	o.Tags = v
}

// GetMemoryUnitCount returns the MemoryUnitCount field value if set, zero value otherwise.
func (o *RetainEventData) GetMemoryUnitCount() int32 {
	if o == nil || IsNil(o.MemoryUnitCount) {
		var ret int32
		return ret
	}
	return *o.MemoryUnitCount
}

// GetMemoryUnitCountOk returns a tuple with the MemoryUnitCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetainEventData) GetMemoryUnitCountOk() (*int32, bool) {
	if o == nil || IsNil(o.MemoryUnitCount) {
		return nil, false
	}
	return o.MemoryUnitCount, true
}

// HasMemoryUnitCount returns a boolean if a field has been set.
func (o *RetainEventData) HasMemoryUnitCount() bool {
	if o != nil && !IsNil(o.MemoryUnitCount) {
		return true
	}

	return false
}

// SetMemoryUnitCount gets a reference to the given int32 and assigns it to the MemoryUnitCount field.
func (o *RetainEventData) SetMemoryUnitCount(v int32) {
	o.MemoryUnitCount = &v
}

func (o RetainEventData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetainEventData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DocumentId) {
		toSerialize["document_id"] = o.DocumentId
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.MemoryUnitCount) {
		toSerialize["memory_unit_count"] = o.MemoryUnitCount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RetainEventData) UnmarshalJSON(data []byte) (err error) {
	varRetainEventData := _RetainEventData{}

	err = json.Unmarshal(data, &varRetainEventData)

	if err != nil {
		return err
	}

	*o = RetainEventData(varRetainEventData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "document_id")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "memory_unit_count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRetainEventData struct {
	value *RetainEventData
	isSet bool
}

func (v NullableRetainEventData) Get() *RetainEventData {
	return v.value
}

func (v *NullableRetainEventData) Set(val *RetainEventData) {
	v.value = val
	v.isSet = true
}

func (v NullableRetainEventData) IsSet() bool {
	return v.isSet
}

func (v *NullableRetainEventData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetainEventData(val *RetainEventData) *NullableRetainEventData {
	return &NullableRetainEventData{value: val, isSet: true}
}

func (v NullableRetainEventData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetainEventData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


