/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BankRestoreResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankRestoreResponse{}

// BankRestoreResponse Response model for restoring a whole-bank backup archive.
type BankRestoreResponse struct {
	BankId string `json:"bank_id"`
	DocumentsImported *int32 `json:"documents_imported,omitempty"`
	FactsImported *int32 `json:"facts_imported,omitempty"`
	ObservationsImported *int32 `json:"observations_imported,omitempty"`
	MentalModelsImported *int32 `json:"mental_models_imported,omitempty"`
	MentalModelHistoryImported *int32 `json:"mental_model_history_imported,omitempty"`
	DirectivesImported *int32 `json:"directives_imported,omitempty"`
	WebhooksImported *int32 `json:"webhooks_imported,omitempty"`
	HistoryRowsImported *int32 `json:"history_rows_imported,omitempty"`
	Status *string `json:"status,omitempty"`
}

type _BankRestoreResponse BankRestoreResponse

// NewBankRestoreResponse instantiates a new BankRestoreResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankRestoreResponse(bankId string) *BankRestoreResponse {
	this := BankRestoreResponse{}
	this.BankId = bankId
	var documentsImported int32 = 0
	this.DocumentsImported = &documentsImported
	var factsImported int32 = 0
	this.FactsImported = &factsImported
	var observationsImported int32 = 0
	this.ObservationsImported = &observationsImported
	var mentalModelsImported int32 = 0
	this.MentalModelsImported = &mentalModelsImported
	var mentalModelHistoryImported int32 = 0
	this.MentalModelHistoryImported = &mentalModelHistoryImported
	var directivesImported int32 = 0
	this.DirectivesImported = &directivesImported
	var webhooksImported int32 = 0
	this.WebhooksImported = &webhooksImported
	var historyRowsImported int32 = 0
	this.HistoryRowsImported = &historyRowsImported
	var status string = "restored"
	this.Status = &status
	return &this
}

// NewBankRestoreResponseWithDefaults instantiates a new BankRestoreResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankRestoreResponseWithDefaults() *BankRestoreResponse {
	this := BankRestoreResponse{}
	var documentsImported int32 = 0
	this.DocumentsImported = &documentsImported
	var factsImported int32 = 0
	this.FactsImported = &factsImported
	var observationsImported int32 = 0
	this.ObservationsImported = &observationsImported
	var mentalModelsImported int32 = 0
	this.MentalModelsImported = &mentalModelsImported
	var mentalModelHistoryImported int32 = 0
	this.MentalModelHistoryImported = &mentalModelHistoryImported
	var directivesImported int32 = 0
	this.DirectivesImported = &directivesImported
	var webhooksImported int32 = 0
	this.WebhooksImported = &webhooksImported
	var historyRowsImported int32 = 0
	this.HistoryRowsImported = &historyRowsImported
	var status string = "restored"
	this.Status = &status
	return &this
}

// GetBankId returns the BankId field value
func (o *BankRestoreResponse) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *BankRestoreResponse) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *BankRestoreResponse) SetBankId(v string) {
	o.BankId = v
}

// GetDocumentsImported returns the DocumentsImported field value if set, zero value otherwise.
func (o *BankRestoreResponse) GetDocumentsImported() int32 {
	if o == nil || IsNil(o.DocumentsImported) {
		var ret int32
		return ret
	}
	return *o.DocumentsImported
}

// GetDocumentsImportedOk returns a tuple with the DocumentsImported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankRestoreResponse) GetDocumentsImportedOk() (*int32, bool) {
	if o == nil || IsNil(o.DocumentsImported) {
		return nil, false
	}
	return o.DocumentsImported, true
}

// HasDocumentsImported returns a boolean if a field has been set.
func (o *BankRestoreResponse) HasDocumentsImported() bool {
	if o != nil && !IsNil(o.DocumentsImported) {
		return true
	}

	return false
}

// SetDocumentsImported gets a reference to the given int32 and assigns it to the DocumentsImported field.
func (o *BankRestoreResponse) SetDocumentsImported(v int32) {
	o.DocumentsImported = &v
}

// GetFactsImported returns the FactsImported field value if set, zero value otherwise.
func (o *BankRestoreResponse) GetFactsImported() int32 {
	if o == nil || IsNil(o.FactsImported) {
		var ret int32
		return ret
	}
	return *o.FactsImported
}

// GetFactsImportedOk returns a tuple with the FactsImported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankRestoreResponse) GetFactsImportedOk() (*int32, bool) {
	if o == nil || IsNil(o.FactsImported) {
		return nil, false
	}
	return o.FactsImported, true
}

// HasFactsImported returns a boolean if a field has been set.
func (o *BankRestoreResponse) HasFactsImported() bool {
	if o != nil && !IsNil(o.FactsImported) {
		return true
	}

	return false
}

// SetFactsImported gets a reference to the given int32 and assigns it to the FactsImported field.
func (o *BankRestoreResponse) SetFactsImported(v int32) {
	o.FactsImported = &v
}

// GetObservationsImported returns the ObservationsImported field value if set, zero value otherwise.
func (o *BankRestoreResponse) GetObservationsImported() int32 {
	if o == nil || IsNil(o.ObservationsImported) {
		var ret int32
		return ret
	}
	return *o.ObservationsImported
}

// GetObservationsImportedOk returns a tuple with the ObservationsImported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankRestoreResponse) GetObservationsImportedOk() (*int32, bool) {
	if o == nil || IsNil(o.ObservationsImported) {
		return nil, false
	}
	return o.ObservationsImported, true
}

// HasObservationsImported returns a boolean if a field has been set.
func (o *BankRestoreResponse) HasObservationsImported() bool {
	if o != nil && !IsNil(o.ObservationsImported) {
		return true
	}

	return false
}

// SetObservationsImported gets a reference to the given int32 and assigns it to the ObservationsImported field.
func (o *BankRestoreResponse) SetObservationsImported(v int32) {
	o.ObservationsImported = &v
}

// GetMentalModelsImported returns the MentalModelsImported field value if set, zero value otherwise.
func (o *BankRestoreResponse) GetMentalModelsImported() int32 {
	if o == nil || IsNil(o.MentalModelsImported) {
		var ret int32
		return ret
	}
	return *o.MentalModelsImported
}

// GetMentalModelsImportedOk returns a tuple with the MentalModelsImported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankRestoreResponse) GetMentalModelsImportedOk() (*int32, bool) {
	if o == nil || IsNil(o.MentalModelsImported) {
		return nil, false
	}
	return o.MentalModelsImported, true
}

// HasMentalModelsImported returns a boolean if a field has been set.
func (o *BankRestoreResponse) HasMentalModelsImported() bool {
	if o != nil && !IsNil(o.MentalModelsImported) {
		return true
	}

	return false
}

// SetMentalModelsImported gets a reference to the given int32 and assigns it to the MentalModelsImported field.
func (o *BankRestoreResponse) SetMentalModelsImported(v int32) {
	o.MentalModelsImported = &v
}

// GetMentalModelHistoryImported returns the MentalModelHistoryImported field value if set, zero value otherwise.
func (o *BankRestoreResponse) GetMentalModelHistoryImported() int32 {
	if o == nil || IsNil(o.MentalModelHistoryImported) {
		var ret int32
		return ret
	}
	return *o.MentalModelHistoryImported
}

// GetMentalModelHistoryImportedOk returns a tuple with the MentalModelHistoryImported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankRestoreResponse) GetMentalModelHistoryImportedOk() (*int32, bool) {
	if o == nil || IsNil(o.MentalModelHistoryImported) {
		return nil, false
	}
	return o.MentalModelHistoryImported, true
}

// HasMentalModelHistoryImported returns a boolean if a field has been set.
func (o *BankRestoreResponse) HasMentalModelHistoryImported() bool {
	if o != nil && !IsNil(o.MentalModelHistoryImported) {
		return true
	}

	return false
}

// SetMentalModelHistoryImported gets a reference to the given int32 and assigns it to the MentalModelHistoryImported field.
func (o *BankRestoreResponse) SetMentalModelHistoryImported(v int32) {
	o.MentalModelHistoryImported = &v
}

// GetDirectivesImported returns the DirectivesImported field value if set, zero value otherwise.
func (o *BankRestoreResponse) GetDirectivesImported() int32 {
	if o == nil || IsNil(o.DirectivesImported) {
		var ret int32
		return ret
	}
	return *o.DirectivesImported
}

// GetDirectivesImportedOk returns a tuple with the DirectivesImported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankRestoreResponse) GetDirectivesImportedOk() (*int32, bool) {
	if o == nil || IsNil(o.DirectivesImported) {
		return nil, false
	}
	return o.DirectivesImported, true
}

// HasDirectivesImported returns a boolean if a field has been set.
func (o *BankRestoreResponse) HasDirectivesImported() bool {
	if o != nil && !IsNil(o.DirectivesImported) {
		return true
	}

	return false
}

// SetDirectivesImported gets a reference to the given int32 and assigns it to the DirectivesImported field.
func (o *BankRestoreResponse) SetDirectivesImported(v int32) {
	o.DirectivesImported = &v
}

// GetWebhooksImported returns the WebhooksImported field value if set, zero value otherwise.
func (o *BankRestoreResponse) GetWebhooksImported() int32 {
	if o == nil || IsNil(o.WebhooksImported) {
		var ret int32
		return ret
	}
	return *o.WebhooksImported
}

// GetWebhooksImportedOk returns a tuple with the WebhooksImported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankRestoreResponse) GetWebhooksImportedOk() (*int32, bool) {
	if o == nil || IsNil(o.WebhooksImported) {
		return nil, false
	}
	return o.WebhooksImported, true
}

// HasWebhooksImported returns a boolean if a field has been set.
func (o *BankRestoreResponse) HasWebhooksImported() bool {
	if o != nil && !IsNil(o.WebhooksImported) {
		return true
	}

	return false
}

// SetWebhooksImported gets a reference to the given int32 and assigns it to the WebhooksImported field.
func (o *BankRestoreResponse) SetWebhooksImported(v int32) {
	o.WebhooksImported = &v
}

// GetHistoryRowsImported returns the HistoryRowsImported field value if set, zero value otherwise.
func (o *BankRestoreResponse) GetHistoryRowsImported() int32 {
	if o == nil || IsNil(o.HistoryRowsImported) {
		var ret int32
		return ret
	}
	return *o.HistoryRowsImported
}

// GetHistoryRowsImportedOk returns a tuple with the HistoryRowsImported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankRestoreResponse) GetHistoryRowsImportedOk() (*int32, bool) {
	if o == nil || IsNil(o.HistoryRowsImported) {
		return nil, false
	}
	return o.HistoryRowsImported, true
}

// HasHistoryRowsImported returns a boolean if a field has been set.
func (o *BankRestoreResponse) HasHistoryRowsImported() bool {
	if o != nil && !IsNil(o.HistoryRowsImported) {
		return true
	}

	return false
}

// SetHistoryRowsImported gets a reference to the given int32 and assigns it to the HistoryRowsImported field.
func (o *BankRestoreResponse) SetHistoryRowsImported(v int32) {
	o.HistoryRowsImported = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BankRestoreResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankRestoreResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BankRestoreResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BankRestoreResponse) SetStatus(v string) {
	o.Status = &v
}

func (o BankRestoreResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankRestoreResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bank_id"] = o.BankId
	if !IsNil(o.DocumentsImported) {
		toSerialize["documents_imported"] = o.DocumentsImported
	}
	if !IsNil(o.FactsImported) {
		toSerialize["facts_imported"] = o.FactsImported
	}
	if !IsNil(o.ObservationsImported) {
		toSerialize["observations_imported"] = o.ObservationsImported
	}
	if !IsNil(o.MentalModelsImported) {
		toSerialize["mental_models_imported"] = o.MentalModelsImported
	}
	if !IsNil(o.MentalModelHistoryImported) {
		toSerialize["mental_model_history_imported"] = o.MentalModelHistoryImported
	}
	if !IsNil(o.DirectivesImported) {
		toSerialize["directives_imported"] = o.DirectivesImported
	}
	if !IsNil(o.WebhooksImported) {
		toSerialize["webhooks_imported"] = o.WebhooksImported
	}
	if !IsNil(o.HistoryRowsImported) {
		toSerialize["history_rows_imported"] = o.HistoryRowsImported
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *BankRestoreResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBankRestoreResponse := _BankRestoreResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBankRestoreResponse)

	if err != nil {
		return err
	}

	*o = BankRestoreResponse(varBankRestoreResponse)

	return err
}

type NullableBankRestoreResponse struct {
	value *BankRestoreResponse
	isSet bool
}

func (v NullableBankRestoreResponse) Get() *BankRestoreResponse {
	return v.value
}

func (v *NullableBankRestoreResponse) Set(val *BankRestoreResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBankRestoreResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBankRestoreResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankRestoreResponse(val *BankRestoreResponse) *NullableBankRestoreResponse {
	return &NullableBankRestoreResponse{value: val, isSet: true}
}

func (v NullableBankRestoreResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankRestoreResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


