/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LLMConcurrencyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMConcurrencyResponse{}

// LLMConcurrencyResponse The process-wide LLM concurrency cap and its live usage.
type LLMConcurrencyResponse struct {
	// Current cap on concurrent LLM calls in this process
	MaxConcurrent int32 `json:"max_concurrent"`
	// The cap from HINDSIGHT_API_LLM_MAX_CONCURRENT, restored by DELETE and on restart
	ConfiguredMaxConcurrent int32 `json:"configured_max_concurrent"`
	// LLM calls currently holding a permit
	InFlight int32 `json:"in_flight"`
	// LLM calls queued for a permit
	Waiting int32 `json:"waiting"`
}

type _LLMConcurrencyResponse LLMConcurrencyResponse

// NewLLMConcurrencyResponse instantiates a new LLMConcurrencyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMConcurrencyResponse(maxConcurrent int32, configuredMaxConcurrent int32, inFlight int32, waiting int32) *LLMConcurrencyResponse {
	this := LLMConcurrencyResponse{}
	this.MaxConcurrent = maxConcurrent
	this.ConfiguredMaxConcurrent = configuredMaxConcurrent
	this.InFlight = inFlight
	this.Waiting = waiting
	return &this
}

// NewLLMConcurrencyResponseWithDefaults instantiates a new LLMConcurrencyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMConcurrencyResponseWithDefaults() *LLMConcurrencyResponse {
	this := LLMConcurrencyResponse{}
	return &this
}

// GetMaxConcurrent returns the MaxConcurrent field value
func (o *LLMConcurrencyResponse) GetMaxConcurrent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxConcurrent
}

// GetMaxConcurrentOk returns a tuple with the MaxConcurrent field value
// and a boolean to check if the value has been set.
func (o *LLMConcurrencyResponse) GetMaxConcurrentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxConcurrent, true
}

// SetMaxConcurrent sets field value
func (o *LLMConcurrencyResponse) SetMaxConcurrent(v int32) {
	o.MaxConcurrent = v
}

// GetConfiguredMaxConcurrent returns the ConfiguredMaxConcurrent field value
func (o *LLMConcurrencyResponse) GetConfiguredMaxConcurrent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ConfiguredMaxConcurrent
}

// GetConfiguredMaxConcurrentOk returns a tuple with the ConfiguredMaxConcurrent field value
// and a boolean to check if the value has been set.
func (o *LLMConcurrencyResponse) GetConfiguredMaxConcurrentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfiguredMaxConcurrent, true
}

// SetConfiguredMaxConcurrent sets field value
func (o *LLMConcurrencyResponse) SetConfiguredMaxConcurrent(v int32) {
	o.ConfiguredMaxConcurrent = v
}

// GetInFlight returns the InFlight field value
func (o *LLMConcurrencyResponse) GetInFlight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InFlight
}

// GetInFlightOk returns a tuple with the InFlight field value
// and a boolean to check if the value has been set.
func (o *LLMConcurrencyResponse) GetInFlightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InFlight, true
}

// SetInFlight sets field value
func (o *LLMConcurrencyResponse) SetInFlight(v int32) {
	o.InFlight = v
}

// GetWaiting returns the Waiting field value
func (o *LLMConcurrencyResponse) GetWaiting() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Waiting
}

// GetWaitingOk returns a tuple with the Waiting field value
// and a boolean to check if the value has been set.
func (o *LLMConcurrencyResponse) GetWaitingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Waiting, true
}

// SetWaiting sets field value
func (o *LLMConcurrencyResponse) SetWaiting(v int32) {
	o.Waiting = v
}

func (o LLMConcurrencyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMConcurrencyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["max_concurrent"] = o.MaxConcurrent
	toSerialize["configured_max_concurrent"] = o.ConfiguredMaxConcurrent
	toSerialize["in_flight"] = o.InFlight
	toSerialize["waiting"] = o.Waiting
	return toSerialize, nil
}

func (o *LLMConcurrencyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"max_concurrent",
		"configured_max_concurrent",
		"in_flight",
		"waiting",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLLMConcurrencyResponse := _LLMConcurrencyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLLMConcurrencyResponse)

	if err != nil {
		return err
	}

	*o = LLMConcurrencyResponse(varLLMConcurrencyResponse)

	return err
}

type NullableLLMConcurrencyResponse struct {
	value *LLMConcurrencyResponse
	isSet bool
}

func (v NullableLLMConcurrencyResponse) Get() *LLMConcurrencyResponse {
	return v.value
}

func (v *NullableLLMConcurrencyResponse) Set(val *LLMConcurrencyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMConcurrencyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMConcurrencyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMConcurrencyResponse(val *LLMConcurrencyResponse) *NullableLLMConcurrencyResponse {
	return &NullableLLMConcurrencyResponse{value: val, isSet: true}
}

func (v NullableLLMConcurrencyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMConcurrencyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


