/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DocumentImageAssetDescriptor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentImageAssetDescriptor{}

// DocumentImageAssetDescriptor A managed image as associated with one recalled document.
type DocumentImageAssetDescriptor struct {
	AssetId string `json:"asset_id"`
	MimeType string `json:"mime_type"`
	SizeBytes int32 `json:"size_bytes"`
	Sha256 string `json:"sha256"`
	Width int32 `json:"width"`
	Height int32 `json:"height"`
	Status ImageAssetStatus `json:"status"`
	DocumentIds []string `json:"document_ids,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Ordinal int32 `json:"ordinal"`
}

type _DocumentImageAssetDescriptor DocumentImageAssetDescriptor

// NewDocumentImageAssetDescriptor instantiates a new DocumentImageAssetDescriptor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentImageAssetDescriptor(assetId string, mimeType string, sizeBytes int32, sha256 string, width int32, height int32, status ImageAssetStatus, createdAt time.Time, updatedAt time.Time, ordinal int32) *DocumentImageAssetDescriptor {
	this := DocumentImageAssetDescriptor{}
	this.AssetId = assetId
	this.MimeType = mimeType
	this.SizeBytes = sizeBytes
	this.Sha256 = sha256
	this.Width = width
	this.Height = height
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Ordinal = ordinal
	return &this
}

// NewDocumentImageAssetDescriptorWithDefaults instantiates a new DocumentImageAssetDescriptor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentImageAssetDescriptorWithDefaults() *DocumentImageAssetDescriptor {
	this := DocumentImageAssetDescriptor{}
	return &this
}

// GetAssetId returns the AssetId field value
func (o *DocumentImageAssetDescriptor) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *DocumentImageAssetDescriptor) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *DocumentImageAssetDescriptor) SetAssetId(v string) {
	o.AssetId = v
}

// GetMimeType returns the MimeType field value
func (o *DocumentImageAssetDescriptor) GetMimeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value
// and a boolean to check if the value has been set.
func (o *DocumentImageAssetDescriptor) GetMimeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MimeType, true
}

// SetMimeType sets field value
func (o *DocumentImageAssetDescriptor) SetMimeType(v string) {
	o.MimeType = v
}

// GetSizeBytes returns the SizeBytes field value
func (o *DocumentImageAssetDescriptor) GetSizeBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value
// and a boolean to check if the value has been set.
func (o *DocumentImageAssetDescriptor) GetSizeBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SizeBytes, true
}

// SetSizeBytes sets field value
func (o *DocumentImageAssetDescriptor) SetSizeBytes(v int32) {
	o.SizeBytes = v
}

// GetSha256 returns the Sha256 field value
func (o *DocumentImageAssetDescriptor) GetSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value
// and a boolean to check if the value has been set.
func (o *DocumentImageAssetDescriptor) GetSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sha256, true
}

// SetSha256 sets field value
func (o *DocumentImageAssetDescriptor) SetSha256(v string) {
	o.Sha256 = v
}

// GetWidth returns the Width field value
func (o *DocumentImageAssetDescriptor) GetWidth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *DocumentImageAssetDescriptor) GetWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *DocumentImageAssetDescriptor) SetWidth(v int32) {
	o.Width = v
}

// GetHeight returns the Height field value
func (o *DocumentImageAssetDescriptor) GetHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *DocumentImageAssetDescriptor) GetHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *DocumentImageAssetDescriptor) SetHeight(v int32) {
	o.Height = v
}

// GetStatus returns the Status field value
func (o *DocumentImageAssetDescriptor) GetStatus() ImageAssetStatus {
	if o == nil {
		var ret ImageAssetStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DocumentImageAssetDescriptor) GetStatusOk() (*ImageAssetStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DocumentImageAssetDescriptor) SetStatus(v ImageAssetStatus) {
	o.Status = v
}

// GetDocumentIds returns the DocumentIds field value if set, zero value otherwise.
func (o *DocumentImageAssetDescriptor) GetDocumentIds() []string {
	if o == nil || IsNil(o.DocumentIds) {
		var ret []string
		return ret
	}
	return o.DocumentIds
}

// GetDocumentIdsOk returns a tuple with the DocumentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentImageAssetDescriptor) GetDocumentIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DocumentIds) {
		return nil, false
	}
	return o.DocumentIds, true
}

// HasDocumentIds returns a boolean if a field has been set.
func (o *DocumentImageAssetDescriptor) HasDocumentIds() bool {
	if o != nil && !IsNil(o.DocumentIds) {
		return true
	}

	return false
}

// SetDocumentIds gets a reference to the given []string and assigns it to the DocumentIds field.
func (o *DocumentImageAssetDescriptor) SetDocumentIds(v []string) {
	o.DocumentIds = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DocumentImageAssetDescriptor) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DocumentImageAssetDescriptor) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DocumentImageAssetDescriptor) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *DocumentImageAssetDescriptor) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *DocumentImageAssetDescriptor) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *DocumentImageAssetDescriptor) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetOrdinal returns the Ordinal field value
func (o *DocumentImageAssetDescriptor) GetOrdinal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ordinal
}

// GetOrdinalOk returns a tuple with the Ordinal field value
// and a boolean to check if the value has been set.
func (o *DocumentImageAssetDescriptor) GetOrdinalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ordinal, true
}

// SetOrdinal sets field value
func (o *DocumentImageAssetDescriptor) SetOrdinal(v int32) {
	o.Ordinal = v
}

func (o DocumentImageAssetDescriptor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentImageAssetDescriptor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset_id"] = o.AssetId
	toSerialize["mime_type"] = o.MimeType
	toSerialize["size_bytes"] = o.SizeBytes
	toSerialize["sha256"] = o.Sha256
	toSerialize["width"] = o.Width
	toSerialize["height"] = o.Height
	toSerialize["status"] = o.Status
	if !IsNil(o.DocumentIds) {
		toSerialize["document_ids"] = o.DocumentIds
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["ordinal"] = o.Ordinal
	return toSerialize, nil
}

func (o *DocumentImageAssetDescriptor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset_id",
		"mime_type",
		"size_bytes",
		"sha256",
		"width",
		"height",
		"status",
		"created_at",
		"updated_at",
		"ordinal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentImageAssetDescriptor := _DocumentImageAssetDescriptor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentImageAssetDescriptor)

	if err != nil {
		return err
	}

	*o = DocumentImageAssetDescriptor(varDocumentImageAssetDescriptor)

	return err
}

type NullableDocumentImageAssetDescriptor struct {
	value *DocumentImageAssetDescriptor
	isSet bool
}

func (v NullableDocumentImageAssetDescriptor) Get() *DocumentImageAssetDescriptor {
	return v.value
}

func (v *NullableDocumentImageAssetDescriptor) Set(val *DocumentImageAssetDescriptor) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentImageAssetDescriptor) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentImageAssetDescriptor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentImageAssetDescriptor(val *DocumentImageAssetDescriptor) *NullableDocumentImageAssetDescriptor {
	return &NullableDocumentImageAssetDescriptor{value: val, isSet: true}
}

func (v NullableDocumentImageAssetDescriptor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentImageAssetDescriptor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


