/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)


// FileParsersValue struct for FileParsersValue
type FileParsersValue struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *FileParsersValue) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(FileParsersValue)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *FileParsersValue) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableFileParsersValue struct {
	value *FileParsersValue
	isSet bool
}

func (v NullableFileParsersValue) Get() *FileParsersValue {
	return v.value
}

func (v *NullableFileParsersValue) Set(val *FileParsersValue) {
	v.value = val
	v.isSet = true
}

func (v NullableFileParsersValue) IsSet() bool {
	return v.isSet
}

func (v *NullableFileParsersValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileParsersValue(val *FileParsersValue) *NullableFileParsersValue {
	return &NullableFileParsersValue{value: val, isSet: true}
}

func (v NullableFileParsersValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileParsersValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


