/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImageRetainAccepted type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageRetainAccepted{}

// ImageRetainAccepted struct for ImageRetainAccepted
type ImageRetainAccepted struct {
	OperationId string `json:"operation_id"`
	DocumentId string `json:"document_id"`
	Status *string `json:"status,omitempty"`
	ImageAssets []ImageAssetDescriptor `json:"image_assets"`
}

type _ImageRetainAccepted ImageRetainAccepted

// NewImageRetainAccepted instantiates a new ImageRetainAccepted object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageRetainAccepted(operationId string, documentId string, imageAssets []ImageAssetDescriptor) *ImageRetainAccepted {
	this := ImageRetainAccepted{}
	this.OperationId = operationId
	this.DocumentId = documentId
	var status string = "pending"
	this.Status = &status
	this.ImageAssets = imageAssets
	return &this
}

// NewImageRetainAcceptedWithDefaults instantiates a new ImageRetainAccepted object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageRetainAcceptedWithDefaults() *ImageRetainAccepted {
	this := ImageRetainAccepted{}
	var status string = "pending"
	this.Status = &status
	return &this
}

// GetOperationId returns the OperationId field value
func (o *ImageRetainAccepted) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *ImageRetainAccepted) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *ImageRetainAccepted) SetOperationId(v string) {
	o.OperationId = v
}

// GetDocumentId returns the DocumentId field value
func (o *ImageRetainAccepted) GetDocumentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value
// and a boolean to check if the value has been set.
func (o *ImageRetainAccepted) GetDocumentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentId, true
}

// SetDocumentId sets field value
func (o *ImageRetainAccepted) SetDocumentId(v string) {
	o.DocumentId = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ImageRetainAccepted) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageRetainAccepted) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ImageRetainAccepted) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ImageRetainAccepted) SetStatus(v string) {
	o.Status = &v
}

// GetImageAssets returns the ImageAssets field value
func (o *ImageRetainAccepted) GetImageAssets() []ImageAssetDescriptor {
	if o == nil {
		var ret []ImageAssetDescriptor
		return ret
	}

	return o.ImageAssets
}

// GetImageAssetsOk returns a tuple with the ImageAssets field value
// and a boolean to check if the value has been set.
func (o *ImageRetainAccepted) GetImageAssetsOk() ([]ImageAssetDescriptor, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImageAssets, true
}

// SetImageAssets sets field value
func (o *ImageRetainAccepted) SetImageAssets(v []ImageAssetDescriptor) {
	o.ImageAssets = v
}

func (o ImageRetainAccepted) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageRetainAccepted) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operation_id"] = o.OperationId
	toSerialize["document_id"] = o.DocumentId
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["image_assets"] = o.ImageAssets
	return toSerialize, nil
}

func (o *ImageRetainAccepted) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operation_id",
		"document_id",
		"image_assets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageRetainAccepted := _ImageRetainAccepted{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageRetainAccepted)

	if err != nil {
		return err
	}

	*o = ImageRetainAccepted(varImageRetainAccepted)

	return err
}

type NullableImageRetainAccepted struct {
	value *ImageRetainAccepted
	isSet bool
}

func (v NullableImageRetainAccepted) Get() *ImageRetainAccepted {
	return v.value
}

func (v *NullableImageRetainAccepted) Set(val *ImageRetainAccepted) {
	v.value = val
	v.isSet = true
}

func (v NullableImageRetainAccepted) IsSet() bool {
	return v.isSet
}

func (v *NullableImageRetainAccepted) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageRetainAccepted(val *ImageRetainAccepted) *NullableImageRetainAccepted {
	return &NullableImageRetainAccepted{value: val, isSet: true}
}

func (v NullableImageRetainAccepted) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageRetainAccepted) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


