/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SemanticCandidateItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SemanticCandidateItem{}

// SemanticCandidateItem A stable memory identifier and its native semantic score.
type SemanticCandidateItem struct {
	Id string `json:"id"`
	Type string `json:"type"`
	Score float32 `json:"score"`
}

type _SemanticCandidateItem SemanticCandidateItem

// NewSemanticCandidateItem instantiates a new SemanticCandidateItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSemanticCandidateItem(id string, type_ string, score float32) *SemanticCandidateItem {
	this := SemanticCandidateItem{}
	this.Id = id
	this.Type = type_
	this.Score = score
	return &this
}

// NewSemanticCandidateItemWithDefaults instantiates a new SemanticCandidateItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSemanticCandidateItemWithDefaults() *SemanticCandidateItem {
	this := SemanticCandidateItem{}
	return &this
}

// GetId returns the Id field value
func (o *SemanticCandidateItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SemanticCandidateItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SemanticCandidateItem) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *SemanticCandidateItem) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SemanticCandidateItem) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SemanticCandidateItem) SetType(v string) {
	o.Type = v
}

// GetScore returns the Score field value
func (o *SemanticCandidateItem) GetScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *SemanticCandidateItem) GetScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *SemanticCandidateItem) SetScore(v float32) {
	o.Score = v
}

func (o SemanticCandidateItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SemanticCandidateItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["score"] = o.Score
	return toSerialize, nil
}

func (o *SemanticCandidateItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"score",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSemanticCandidateItem := _SemanticCandidateItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSemanticCandidateItem)

	if err != nil {
		return err
	}

	*o = SemanticCandidateItem(varSemanticCandidateItem)

	return err
}

type NullableSemanticCandidateItem struct {
	value *SemanticCandidateItem
	isSet bool
}

func (v NullableSemanticCandidateItem) Get() *SemanticCandidateItem {
	return v.value
}

func (v *NullableSemanticCandidateItem) Set(val *SemanticCandidateItem) {
	v.value = val
	v.isSet = true
}

func (v NullableSemanticCandidateItem) IsSet() bool {
	return v.isSet
}

func (v *NullableSemanticCandidateItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSemanticCandidateItem(val *SemanticCandidateItem) *NullableSemanticCandidateItem {
	return &NullableSemanticCandidateItem{value: val, isSet: true}
}

func (v NullableSemanticCandidateItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSemanticCandidateItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
