/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LLMConcurrencyUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMConcurrencyUpdate{}

// LLMConcurrencyUpdate Request model for changing the process-wide LLM concurrency cap.
type LLMConcurrencyUpdate struct {
	// New cap on concurrent LLM calls in this process. Lowering it lets in-flight calls finish and starts no new call until usage is under the cap; raising it starts waiting calls immediately.
	MaxConcurrent int32 `json:"max_concurrent"`
}

type _LLMConcurrencyUpdate LLMConcurrencyUpdate

// NewLLMConcurrencyUpdate instantiates a new LLMConcurrencyUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMConcurrencyUpdate(maxConcurrent int32) *LLMConcurrencyUpdate {
	this := LLMConcurrencyUpdate{}
	this.MaxConcurrent = maxConcurrent
	return &this
}

// NewLLMConcurrencyUpdateWithDefaults instantiates a new LLMConcurrencyUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMConcurrencyUpdateWithDefaults() *LLMConcurrencyUpdate {
	this := LLMConcurrencyUpdate{}
	return &this
}

// GetMaxConcurrent returns the MaxConcurrent field value
func (o *LLMConcurrencyUpdate) GetMaxConcurrent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxConcurrent
}

// GetMaxConcurrentOk returns a tuple with the MaxConcurrent field value
// and a boolean to check if the value has been set.
func (o *LLMConcurrencyUpdate) GetMaxConcurrentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxConcurrent, true
}

// SetMaxConcurrent sets field value
func (o *LLMConcurrencyUpdate) SetMaxConcurrent(v int32) {
	o.MaxConcurrent = v
}

func (o LLMConcurrencyUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMConcurrencyUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["max_concurrent"] = o.MaxConcurrent
	return toSerialize, nil
}

func (o *LLMConcurrencyUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"max_concurrent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLLMConcurrencyUpdate := _LLMConcurrencyUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLLMConcurrencyUpdate)

	if err != nil {
		return err
	}

	*o = LLMConcurrencyUpdate(varLLMConcurrencyUpdate)

	return err
}

type NullableLLMConcurrencyUpdate struct {
	value *LLMConcurrencyUpdate
	isSet bool
}

func (v NullableLLMConcurrencyUpdate) Get() *LLMConcurrencyUpdate {
	return v.value
}

func (v *NullableLLMConcurrencyUpdate) Set(val *LLMConcurrencyUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMConcurrencyUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMConcurrencyUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMConcurrencyUpdate(val *LLMConcurrencyUpdate) *NullableLLMConcurrencyUpdate {
	return &NullableLLMConcurrencyUpdate{value: val, isSet: true}
}

func (v NullableLLMConcurrencyUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMConcurrencyUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


