/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
)

// checks if the PromptPreviewRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptPreviewRequest{}

// PromptPreviewRequest Request to render the prompts an operation would send, without calling an LLM.  Every field is optional: with an empty body you get the bank's current prompts with bracketed placeholders where the runtime data (the chunk, the facts, the question) would go. The mission/config fields override the bank's stored values for this call only, so the control plane can preview an unsaved edit.
type PromptPreviewRequest struct {
	// Which operation's prompts to render.
	Operation *string `json:"operation,omitempty"`
	Content NullableString `json:"content,omitempty"`
	Context NullableString `json:"context,omitempty"`
	Timestamp NullableTime `json:"timestamp,omitempty"`
	ExistingObservations NullableString `json:"existing_observations,omitempty"`
	// Whether search_observations is in the reflect tool list (reflect only).
	IncludeObservations *bool `json:"include_observations,omitempty"`
	// Whether the bank has mental models to search (reflect only).
	HasMentalModels *bool `json:"has_mental_models,omitempty"`
	Budget NullableString `json:"budget,omitempty"`
	RetainMission NullableString `json:"retain_mission,omitempty"`
	RetainExtractionMode NullableString `json:"retain_extraction_mode,omitempty"`
	RetainCustomInstructions NullableString `json:"retain_custom_instructions,omitempty"`
	RetainExtractCausalLinks NullableBool `json:"retain_extract_causal_links,omitempty"`
	RetainChunkSize NullableInt32 `json:"retain_chunk_size,omitempty"`
	EntityLabels []LabelGroupInput `json:"entity_labels,omitempty"`
	EntitiesAllowFreeForm NullableBool `json:"entities_allow_free_form,omitempty"`
	ObservationsMission NullableString `json:"observations_mission,omitempty"`
	ReflectMission NullableString `json:"reflect_mission,omitempty"`
	LlmOutputLanguage NullableString `json:"llm_output_language,omitempty"`
}

// NewPromptPreviewRequest instantiates a new PromptPreviewRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptPreviewRequest() *PromptPreviewRequest {
	this := PromptPreviewRequest{}
	var operation string = "retain"
	this.Operation = &operation
	var includeObservations bool = true
	this.IncludeObservations = &includeObservations
	var hasMentalModels bool = true
	this.HasMentalModels = &hasMentalModels
	return &this
}

// NewPromptPreviewRequestWithDefaults instantiates a new PromptPreviewRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptPreviewRequestWithDefaults() *PromptPreviewRequest {
	this := PromptPreviewRequest{}
	var operation string = "retain"
	this.Operation = &operation
	var includeObservations bool = true
	this.IncludeObservations = &includeObservations
	var hasMentalModels bool = true
	this.HasMentalModels = &hasMentalModels
	return &this
}

// GetOperation returns the Operation field value if set, zero value otherwise.
func (o *PromptPreviewRequest) GetOperation() string {
	if o == nil || IsNil(o.Operation) {
		var ret string
		return ret
	}
	return *o.Operation
}

// GetOperationOk returns a tuple with the Operation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptPreviewRequest) GetOperationOk() (*string, bool) {
	if o == nil || IsNil(o.Operation) {
		return nil, false
	}
	return o.Operation, true
}

// HasOperation returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasOperation() bool {
	if o != nil && !IsNil(o.Operation) {
		return true
	}

	return false
}

// SetOperation gets a reference to the given string and assigns it to the Operation field.
func (o *PromptPreviewRequest) SetOperation(v string) {
	o.Operation = &v
}

// GetContent returns the Content field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetContent() string {
	if o == nil || IsNil(o.Content.Get()) {
		var ret string
		return ret
	}
	return *o.Content.Get()
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Content.Get(), o.Content.IsSet()
}

// HasContent returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasContent() bool {
	if o != nil && o.Content.IsSet() {
		return true
	}

	return false
}

// SetContent gets a reference to the given NullableString and assigns it to the Content field.
func (o *PromptPreviewRequest) SetContent(v string) {
	o.Content.Set(&v)
}
// SetContentNil sets the value for Content to be an explicit nil
func (o *PromptPreviewRequest) SetContentNil() {
	o.Content.Set(nil)
}

// UnsetContent ensures that no value is present for Content, not even an explicit nil
func (o *PromptPreviewRequest) UnsetContent() {
	o.Content.Unset()
}

// GetContext returns the Context field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetContext() string {
	if o == nil || IsNil(o.Context.Get()) {
		var ret string
		return ret
	}
	return *o.Context.Get()
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Context.Get(), o.Context.IsSet()
}

// HasContext returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasContext() bool {
	if o != nil && o.Context.IsSet() {
		return true
	}

	return false
}

// SetContext gets a reference to the given NullableString and assigns it to the Context field.
func (o *PromptPreviewRequest) SetContext(v string) {
	o.Context.Set(&v)
}
// SetContextNil sets the value for Context to be an explicit nil
func (o *PromptPreviewRequest) SetContextNil() {
	o.Context.Set(nil)
}

// UnsetContext ensures that no value is present for Context, not even an explicit nil
func (o *PromptPreviewRequest) UnsetContext() {
	o.Context.Unset()
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableTime and assigns it to the Timestamp field.
func (o *PromptPreviewRequest) SetTimestamp(v time.Time) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *PromptPreviewRequest) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *PromptPreviewRequest) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetExistingObservations returns the ExistingObservations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetExistingObservations() string {
	if o == nil || IsNil(o.ExistingObservations.Get()) {
		var ret string
		return ret
	}
	return *o.ExistingObservations.Get()
}

// GetExistingObservationsOk returns a tuple with the ExistingObservations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetExistingObservationsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExistingObservations.Get(), o.ExistingObservations.IsSet()
}

// HasExistingObservations returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasExistingObservations() bool {
	if o != nil && o.ExistingObservations.IsSet() {
		return true
	}

	return false
}

// SetExistingObservations gets a reference to the given NullableString and assigns it to the ExistingObservations field.
func (o *PromptPreviewRequest) SetExistingObservations(v string) {
	o.ExistingObservations.Set(&v)
}
// SetExistingObservationsNil sets the value for ExistingObservations to be an explicit nil
func (o *PromptPreviewRequest) SetExistingObservationsNil() {
	o.ExistingObservations.Set(nil)
}

// UnsetExistingObservations ensures that no value is present for ExistingObservations, not even an explicit nil
func (o *PromptPreviewRequest) UnsetExistingObservations() {
	o.ExistingObservations.Unset()
}

// GetIncludeObservations returns the IncludeObservations field value if set, zero value otherwise.
func (o *PromptPreviewRequest) GetIncludeObservations() bool {
	if o == nil || IsNil(o.IncludeObservations) {
		var ret bool
		return ret
	}
	return *o.IncludeObservations
}

// GetIncludeObservationsOk returns a tuple with the IncludeObservations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptPreviewRequest) GetIncludeObservationsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeObservations) {
		return nil, false
	}
	return o.IncludeObservations, true
}

// HasIncludeObservations returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasIncludeObservations() bool {
	if o != nil && !IsNil(o.IncludeObservations) {
		return true
	}

	return false
}

// SetIncludeObservations gets a reference to the given bool and assigns it to the IncludeObservations field.
func (o *PromptPreviewRequest) SetIncludeObservations(v bool) {
	o.IncludeObservations = &v
}

// GetHasMentalModels returns the HasMentalModels field value if set, zero value otherwise.
func (o *PromptPreviewRequest) GetHasMentalModels() bool {
	if o == nil || IsNil(o.HasMentalModels) {
		var ret bool
		return ret
	}
	return *o.HasMentalModels
}

// GetHasMentalModelsOk returns a tuple with the HasMentalModels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptPreviewRequest) GetHasMentalModelsOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMentalModels) {
		return nil, false
	}
	return o.HasMentalModels, true
}

// HasHasMentalModels returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasHasMentalModels() bool {
	if o != nil && !IsNil(o.HasMentalModels) {
		return true
	}

	return false
}

// SetHasMentalModels gets a reference to the given bool and assigns it to the HasMentalModels field.
func (o *PromptPreviewRequest) SetHasMentalModels(v bool) {
	o.HasMentalModels = &v
}

// GetBudget returns the Budget field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetBudget() string {
	if o == nil || IsNil(o.Budget.Get()) {
		var ret string
		return ret
	}
	return *o.Budget.Get()
}

// GetBudgetOk returns a tuple with the Budget field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetBudgetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Budget.Get(), o.Budget.IsSet()
}

// HasBudget returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasBudget() bool {
	if o != nil && o.Budget.IsSet() {
		return true
	}

	return false
}

// SetBudget gets a reference to the given NullableString and assigns it to the Budget field.
func (o *PromptPreviewRequest) SetBudget(v string) {
	o.Budget.Set(&v)
}
// SetBudgetNil sets the value for Budget to be an explicit nil
func (o *PromptPreviewRequest) SetBudgetNil() {
	o.Budget.Set(nil)
}

// UnsetBudget ensures that no value is present for Budget, not even an explicit nil
func (o *PromptPreviewRequest) UnsetBudget() {
	o.Budget.Unset()
}

// GetRetainMission returns the RetainMission field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetRetainMission() string {
	if o == nil || IsNil(o.RetainMission.Get()) {
		var ret string
		return ret
	}
	return *o.RetainMission.Get()
}

// GetRetainMissionOk returns a tuple with the RetainMission field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetRetainMissionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainMission.Get(), o.RetainMission.IsSet()
}

// HasRetainMission returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasRetainMission() bool {
	if o != nil && o.RetainMission.IsSet() {
		return true
	}

	return false
}

// SetRetainMission gets a reference to the given NullableString and assigns it to the RetainMission field.
func (o *PromptPreviewRequest) SetRetainMission(v string) {
	o.RetainMission.Set(&v)
}
// SetRetainMissionNil sets the value for RetainMission to be an explicit nil
func (o *PromptPreviewRequest) SetRetainMissionNil() {
	o.RetainMission.Set(nil)
}

// UnsetRetainMission ensures that no value is present for RetainMission, not even an explicit nil
func (o *PromptPreviewRequest) UnsetRetainMission() {
	o.RetainMission.Unset()
}

// GetRetainExtractionMode returns the RetainExtractionMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetRetainExtractionMode() string {
	if o == nil || IsNil(o.RetainExtractionMode.Get()) {
		var ret string
		return ret
	}
	return *o.RetainExtractionMode.Get()
}

// GetRetainExtractionModeOk returns a tuple with the RetainExtractionMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetRetainExtractionModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainExtractionMode.Get(), o.RetainExtractionMode.IsSet()
}

// HasRetainExtractionMode returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasRetainExtractionMode() bool {
	if o != nil && o.RetainExtractionMode.IsSet() {
		return true
	}

	return false
}

// SetRetainExtractionMode gets a reference to the given NullableString and assigns it to the RetainExtractionMode field.
func (o *PromptPreviewRequest) SetRetainExtractionMode(v string) {
	o.RetainExtractionMode.Set(&v)
}
// SetRetainExtractionModeNil sets the value for RetainExtractionMode to be an explicit nil
func (o *PromptPreviewRequest) SetRetainExtractionModeNil() {
	o.RetainExtractionMode.Set(nil)
}

// UnsetRetainExtractionMode ensures that no value is present for RetainExtractionMode, not even an explicit nil
func (o *PromptPreviewRequest) UnsetRetainExtractionMode() {
	o.RetainExtractionMode.Unset()
}

// GetRetainCustomInstructions returns the RetainCustomInstructions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetRetainCustomInstructions() string {
	if o == nil || IsNil(o.RetainCustomInstructions.Get()) {
		var ret string
		return ret
	}
	return *o.RetainCustomInstructions.Get()
}

// GetRetainCustomInstructionsOk returns a tuple with the RetainCustomInstructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetRetainCustomInstructionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainCustomInstructions.Get(), o.RetainCustomInstructions.IsSet()
}

// HasRetainCustomInstructions returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasRetainCustomInstructions() bool {
	if o != nil && o.RetainCustomInstructions.IsSet() {
		return true
	}

	return false
}

// SetRetainCustomInstructions gets a reference to the given NullableString and assigns it to the RetainCustomInstructions field.
func (o *PromptPreviewRequest) SetRetainCustomInstructions(v string) {
	o.RetainCustomInstructions.Set(&v)
}
// SetRetainCustomInstructionsNil sets the value for RetainCustomInstructions to be an explicit nil
func (o *PromptPreviewRequest) SetRetainCustomInstructionsNil() {
	o.RetainCustomInstructions.Set(nil)
}

// UnsetRetainCustomInstructions ensures that no value is present for RetainCustomInstructions, not even an explicit nil
func (o *PromptPreviewRequest) UnsetRetainCustomInstructions() {
	o.RetainCustomInstructions.Unset()
}

// GetRetainExtractCausalLinks returns the RetainExtractCausalLinks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetRetainExtractCausalLinks() bool {
	if o == nil || IsNil(o.RetainExtractCausalLinks.Get()) {
		var ret bool
		return ret
	}
	return *o.RetainExtractCausalLinks.Get()
}

// GetRetainExtractCausalLinksOk returns a tuple with the RetainExtractCausalLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetRetainExtractCausalLinksOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainExtractCausalLinks.Get(), o.RetainExtractCausalLinks.IsSet()
}

// HasRetainExtractCausalLinks returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasRetainExtractCausalLinks() bool {
	if o != nil && o.RetainExtractCausalLinks.IsSet() {
		return true
	}

	return false
}

// SetRetainExtractCausalLinks gets a reference to the given NullableBool and assigns it to the RetainExtractCausalLinks field.
func (o *PromptPreviewRequest) SetRetainExtractCausalLinks(v bool) {
	o.RetainExtractCausalLinks.Set(&v)
}
// SetRetainExtractCausalLinksNil sets the value for RetainExtractCausalLinks to be an explicit nil
func (o *PromptPreviewRequest) SetRetainExtractCausalLinksNil() {
	o.RetainExtractCausalLinks.Set(nil)
}

// UnsetRetainExtractCausalLinks ensures that no value is present for RetainExtractCausalLinks, not even an explicit nil
func (o *PromptPreviewRequest) UnsetRetainExtractCausalLinks() {
	o.RetainExtractCausalLinks.Unset()
}

// GetRetainChunkSize returns the RetainChunkSize field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetRetainChunkSize() int32 {
	if o == nil || IsNil(o.RetainChunkSize.Get()) {
		var ret int32
		return ret
	}
	return *o.RetainChunkSize.Get()
}

// GetRetainChunkSizeOk returns a tuple with the RetainChunkSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetRetainChunkSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainChunkSize.Get(), o.RetainChunkSize.IsSet()
}

// HasRetainChunkSize returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasRetainChunkSize() bool {
	if o != nil && o.RetainChunkSize.IsSet() {
		return true
	}

	return false
}

// SetRetainChunkSize gets a reference to the given NullableInt32 and assigns it to the RetainChunkSize field.
func (o *PromptPreviewRequest) SetRetainChunkSize(v int32) {
	o.RetainChunkSize.Set(&v)
}
// SetRetainChunkSizeNil sets the value for RetainChunkSize to be an explicit nil
func (o *PromptPreviewRequest) SetRetainChunkSizeNil() {
	o.RetainChunkSize.Set(nil)
}

// UnsetRetainChunkSize ensures that no value is present for RetainChunkSize, not even an explicit nil
func (o *PromptPreviewRequest) UnsetRetainChunkSize() {
	o.RetainChunkSize.Unset()
}

// GetEntityLabels returns the EntityLabels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetEntityLabels() []LabelGroupInput {
	if o == nil {
		var ret []LabelGroupInput
		return ret
	}
	return o.EntityLabels
}

// GetEntityLabelsOk returns a tuple with the EntityLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetEntityLabelsOk() ([]LabelGroupInput, bool) {
	if o == nil || IsNil(o.EntityLabels) {
		return nil, false
	}
	return o.EntityLabels, true
}

// HasEntityLabels returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasEntityLabels() bool {
	if o != nil && !IsNil(o.EntityLabels) {
		return true
	}

	return false
}

// SetEntityLabels gets a reference to the given []LabelGroupInput and assigns it to the EntityLabels field.
func (o *PromptPreviewRequest) SetEntityLabels(v []LabelGroupInput) {
	o.EntityLabels = v
}

// GetEntitiesAllowFreeForm returns the EntitiesAllowFreeForm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetEntitiesAllowFreeForm() bool {
	if o == nil || IsNil(o.EntitiesAllowFreeForm.Get()) {
		var ret bool
		return ret
	}
	return *o.EntitiesAllowFreeForm.Get()
}

// GetEntitiesAllowFreeFormOk returns a tuple with the EntitiesAllowFreeForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetEntitiesAllowFreeFormOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.EntitiesAllowFreeForm.Get(), o.EntitiesAllowFreeForm.IsSet()
}

// HasEntitiesAllowFreeForm returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasEntitiesAllowFreeForm() bool {
	if o != nil && o.EntitiesAllowFreeForm.IsSet() {
		return true
	}

	return false
}

// SetEntitiesAllowFreeForm gets a reference to the given NullableBool and assigns it to the EntitiesAllowFreeForm field.
func (o *PromptPreviewRequest) SetEntitiesAllowFreeForm(v bool) {
	o.EntitiesAllowFreeForm.Set(&v)
}
// SetEntitiesAllowFreeFormNil sets the value for EntitiesAllowFreeForm to be an explicit nil
func (o *PromptPreviewRequest) SetEntitiesAllowFreeFormNil() {
	o.EntitiesAllowFreeForm.Set(nil)
}

// UnsetEntitiesAllowFreeForm ensures that no value is present for EntitiesAllowFreeForm, not even an explicit nil
func (o *PromptPreviewRequest) UnsetEntitiesAllowFreeForm() {
	o.EntitiesAllowFreeForm.Unset()
}

// GetObservationsMission returns the ObservationsMission field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetObservationsMission() string {
	if o == nil || IsNil(o.ObservationsMission.Get()) {
		var ret string
		return ret
	}
	return *o.ObservationsMission.Get()
}

// GetObservationsMissionOk returns a tuple with the ObservationsMission field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetObservationsMissionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ObservationsMission.Get(), o.ObservationsMission.IsSet()
}

// HasObservationsMission returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasObservationsMission() bool {
	if o != nil && o.ObservationsMission.IsSet() {
		return true
	}

	return false
}

// SetObservationsMission gets a reference to the given NullableString and assigns it to the ObservationsMission field.
func (o *PromptPreviewRequest) SetObservationsMission(v string) {
	o.ObservationsMission.Set(&v)
}
// SetObservationsMissionNil sets the value for ObservationsMission to be an explicit nil
func (o *PromptPreviewRequest) SetObservationsMissionNil() {
	o.ObservationsMission.Set(nil)
}

// UnsetObservationsMission ensures that no value is present for ObservationsMission, not even an explicit nil
func (o *PromptPreviewRequest) UnsetObservationsMission() {
	o.ObservationsMission.Unset()
}

// GetReflectMission returns the ReflectMission field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetReflectMission() string {
	if o == nil || IsNil(o.ReflectMission.Get()) {
		var ret string
		return ret
	}
	return *o.ReflectMission.Get()
}

// GetReflectMissionOk returns a tuple with the ReflectMission field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetReflectMissionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReflectMission.Get(), o.ReflectMission.IsSet()
}

// HasReflectMission returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasReflectMission() bool {
	if o != nil && o.ReflectMission.IsSet() {
		return true
	}

	return false
}

// SetReflectMission gets a reference to the given NullableString and assigns it to the ReflectMission field.
func (o *PromptPreviewRequest) SetReflectMission(v string) {
	o.ReflectMission.Set(&v)
}
// SetReflectMissionNil sets the value for ReflectMission to be an explicit nil
func (o *PromptPreviewRequest) SetReflectMissionNil() {
	o.ReflectMission.Set(nil)
}

// UnsetReflectMission ensures that no value is present for ReflectMission, not even an explicit nil
func (o *PromptPreviewRequest) UnsetReflectMission() {
	o.ReflectMission.Unset()
}

// GetLlmOutputLanguage returns the LlmOutputLanguage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewRequest) GetLlmOutputLanguage() string {
	if o == nil || IsNil(o.LlmOutputLanguage.Get()) {
		var ret string
		return ret
	}
	return *o.LlmOutputLanguage.Get()
}

// GetLlmOutputLanguageOk returns a tuple with the LlmOutputLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewRequest) GetLlmOutputLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LlmOutputLanguage.Get(), o.LlmOutputLanguage.IsSet()
}

// HasLlmOutputLanguage returns a boolean if a field has been set.
func (o *PromptPreviewRequest) HasLlmOutputLanguage() bool {
	if o != nil && o.LlmOutputLanguage.IsSet() {
		return true
	}

	return false
}

// SetLlmOutputLanguage gets a reference to the given NullableString and assigns it to the LlmOutputLanguage field.
func (o *PromptPreviewRequest) SetLlmOutputLanguage(v string) {
	o.LlmOutputLanguage.Set(&v)
}
// SetLlmOutputLanguageNil sets the value for LlmOutputLanguage to be an explicit nil
func (o *PromptPreviewRequest) SetLlmOutputLanguageNil() {
	o.LlmOutputLanguage.Set(nil)
}

// UnsetLlmOutputLanguage ensures that no value is present for LlmOutputLanguage, not even an explicit nil
func (o *PromptPreviewRequest) UnsetLlmOutputLanguage() {
	o.LlmOutputLanguage.Unset()
}

func (o PromptPreviewRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptPreviewRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Operation) {
		toSerialize["operation"] = o.Operation
	}
	if o.Content.IsSet() {
		toSerialize["content"] = o.Content.Get()
	}
	if o.Context.IsSet() {
		toSerialize["context"] = o.Context.Get()
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.ExistingObservations.IsSet() {
		toSerialize["existing_observations"] = o.ExistingObservations.Get()
	}
	if !IsNil(o.IncludeObservations) {
		toSerialize["include_observations"] = o.IncludeObservations
	}
	if !IsNil(o.HasMentalModels) {
		toSerialize["has_mental_models"] = o.HasMentalModels
	}
	if o.Budget.IsSet() {
		toSerialize["budget"] = o.Budget.Get()
	}
	if o.RetainMission.IsSet() {
		toSerialize["retain_mission"] = o.RetainMission.Get()
	}
	if o.RetainExtractionMode.IsSet() {
		toSerialize["retain_extraction_mode"] = o.RetainExtractionMode.Get()
	}
	if o.RetainCustomInstructions.IsSet() {
		toSerialize["retain_custom_instructions"] = o.RetainCustomInstructions.Get()
	}
	if o.RetainExtractCausalLinks.IsSet() {
		toSerialize["retain_extract_causal_links"] = o.RetainExtractCausalLinks.Get()
	}
	if o.RetainChunkSize.IsSet() {
		toSerialize["retain_chunk_size"] = o.RetainChunkSize.Get()
	}
	if o.EntityLabels != nil {
		toSerialize["entity_labels"] = o.EntityLabels
	}
	if o.EntitiesAllowFreeForm.IsSet() {
		toSerialize["entities_allow_free_form"] = o.EntitiesAllowFreeForm.Get()
	}
	if o.ObservationsMission.IsSet() {
		toSerialize["observations_mission"] = o.ObservationsMission.Get()
	}
	if o.ReflectMission.IsSet() {
		toSerialize["reflect_mission"] = o.ReflectMission.Get()
	}
	if o.LlmOutputLanguage.IsSet() {
		toSerialize["llm_output_language"] = o.LlmOutputLanguage.Get()
	}
	return toSerialize, nil
}

type NullablePromptPreviewRequest struct {
	value *PromptPreviewRequest
	isSet bool
}

func (v NullablePromptPreviewRequest) Get() *PromptPreviewRequest {
	return v.value
}

func (v *NullablePromptPreviewRequest) Set(val *PromptPreviewRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptPreviewRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptPreviewRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptPreviewRequest(val *PromptPreviewRequest) *NullablePromptPreviewRequest {
	return &NullablePromptPreviewRequest{value: val, isSet: true}
}

func (v NullablePromptPreviewRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptPreviewRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


