/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FeaturesInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeaturesInfo{}

// FeaturesInfo Feature flags indicating which capabilities are enabled.
type FeaturesInfo struct {
	// Configured authorization deployment profile
	AuthzProfile *string `json:"authz_profile,omitempty"`
	TenantExtension NullableString `json:"tenant_extension,omitempty"`
	OperationValidatorExtension NullableString `json:"operation_validator_extension,omitempty"`
	// Whether the supabase_org profile is fully configured
	SupabaseOrgReady *bool `json:"supabase_org_ready,omitempty"`
	// Whether observations (auto-consolidation) are enabled
	Observations bool `json:"observations"`
	// Whether MCP (Model Context Protocol) server is enabled
	Mcp bool `json:"mcp"`
	// Whether the background worker is enabled
	Worker bool `json:"worker"`
	// Whether per-bank configuration API is enabled
	BankConfigApi bool `json:"bank_config_api"`
	// Whether the per-bank LLM connectivity probe is enabled
	BankLlmHealth bool `json:"bank_llm_health"`
	// Whether file upload/conversion API is enabled
	FileUploadApi bool `json:"file_upload_api"`
	// Whether the document export endpoint is enabled
	DocumentExportApi bool `json:"document_export_api"`
	// Whether the document import endpoint is enabled
	DocumentImportApi bool `json:"document_import_api"`
	// Whether audit logging is enabled
	AuditLog bool `json:"audit_log"`
	// Whether per-bank LLM request tracing is enabled
	LlmTrace bool `json:"llm_trace"`
	// Whether raw source text is persisted. When false, document/chunk source text is not stored.
	StoreDocumentText bool `json:"store_document_text"`
}

type _FeaturesInfo FeaturesInfo

// NewFeaturesInfo instantiates a new FeaturesInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeaturesInfo(observations bool, mcp bool, worker bool, bankConfigApi bool, bankLlmHealth bool, fileUploadApi bool, documentExportApi bool, documentImportApi bool, auditLog bool, llmTrace bool, storeDocumentText bool) *FeaturesInfo {
	this := FeaturesInfo{}
	var authzProfile string = "disabled"
	this.AuthzProfile = &authzProfile
	var supabaseOrgReady bool = false
	this.SupabaseOrgReady = &supabaseOrgReady
	this.Observations = observations
	this.Mcp = mcp
	this.Worker = worker
	this.BankConfigApi = bankConfigApi
	this.BankLlmHealth = bankLlmHealth
	this.FileUploadApi = fileUploadApi
	this.DocumentExportApi = documentExportApi
	this.DocumentImportApi = documentImportApi
	this.AuditLog = auditLog
	this.LlmTrace = llmTrace
	this.StoreDocumentText = storeDocumentText
	return &this
}

// NewFeaturesInfoWithDefaults instantiates a new FeaturesInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeaturesInfoWithDefaults() *FeaturesInfo {
	this := FeaturesInfo{}
	var authzProfile string = "disabled"
	this.AuthzProfile = &authzProfile
	var supabaseOrgReady bool = false
	this.SupabaseOrgReady = &supabaseOrgReady
	return &this
}

// GetAuthzProfile returns the AuthzProfile field value if set, zero value otherwise.
func (o *FeaturesInfo) GetAuthzProfile() string {
	if o == nil || IsNil(o.AuthzProfile) {
		var ret string
		return ret
	}
	return *o.AuthzProfile
}

// GetAuthzProfileOk returns a tuple with the AuthzProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetAuthzProfileOk() (*string, bool) {
	if o == nil || IsNil(o.AuthzProfile) {
		return nil, false
	}
	return o.AuthzProfile, true
}

// HasAuthzProfile returns a boolean if a field has been set.
func (o *FeaturesInfo) HasAuthzProfile() bool {
	if o != nil && !IsNil(o.AuthzProfile) {
		return true
	}

	return false
}

// SetAuthzProfile gets a reference to the given string and assigns it to the AuthzProfile field.
func (o *FeaturesInfo) SetAuthzProfile(v string) {
	o.AuthzProfile = &v
}

// GetTenantExtension returns the TenantExtension field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FeaturesInfo) GetTenantExtension() string {
	if o == nil || IsNil(o.TenantExtension.Get()) {
		var ret string
		return ret
	}
	return *o.TenantExtension.Get()
}

// GetTenantExtensionOk returns a tuple with the TenantExtension field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FeaturesInfo) GetTenantExtensionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantExtension.Get(), o.TenantExtension.IsSet()
}

// HasTenantExtension returns a boolean if a field has been set.
func (o *FeaturesInfo) HasTenantExtension() bool {
	if o != nil && o.TenantExtension.IsSet() {
		return true
	}

	return false
}

// SetTenantExtension gets a reference to the given NullableString and assigns it to the TenantExtension field.
func (o *FeaturesInfo) SetTenantExtension(v string) {
	o.TenantExtension.Set(&v)
}
// SetTenantExtensionNil sets the value for TenantExtension to be an explicit nil
func (o *FeaturesInfo) SetTenantExtensionNil() {
	o.TenantExtension.Set(nil)
}

// UnsetTenantExtension ensures that no value is present for TenantExtension, not even an explicit nil
func (o *FeaturesInfo) UnsetTenantExtension() {
	o.TenantExtension.Unset()
}

// GetOperationValidatorExtension returns the OperationValidatorExtension field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FeaturesInfo) GetOperationValidatorExtension() string {
	if o == nil || IsNil(o.OperationValidatorExtension.Get()) {
		var ret string
		return ret
	}
	return *o.OperationValidatorExtension.Get()
}

// GetOperationValidatorExtensionOk returns a tuple with the OperationValidatorExtension field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FeaturesInfo) GetOperationValidatorExtensionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OperationValidatorExtension.Get(), o.OperationValidatorExtension.IsSet()
}

// HasOperationValidatorExtension returns a boolean if a field has been set.
func (o *FeaturesInfo) HasOperationValidatorExtension() bool {
	if o != nil && o.OperationValidatorExtension.IsSet() {
		return true
	}

	return false
}

// SetOperationValidatorExtension gets a reference to the given NullableString and assigns it to the OperationValidatorExtension field.
func (o *FeaturesInfo) SetOperationValidatorExtension(v string) {
	o.OperationValidatorExtension.Set(&v)
}
// SetOperationValidatorExtensionNil sets the value for OperationValidatorExtension to be an explicit nil
func (o *FeaturesInfo) SetOperationValidatorExtensionNil() {
	o.OperationValidatorExtension.Set(nil)
}

// UnsetOperationValidatorExtension ensures that no value is present for OperationValidatorExtension, not even an explicit nil
func (o *FeaturesInfo) UnsetOperationValidatorExtension() {
	o.OperationValidatorExtension.Unset()
}

// GetSupabaseOrgReady returns the SupabaseOrgReady field value if set, zero value otherwise.
func (o *FeaturesInfo) GetSupabaseOrgReady() bool {
	if o == nil || IsNil(o.SupabaseOrgReady) {
		var ret bool
		return ret
	}
	return *o.SupabaseOrgReady
}

// GetSupabaseOrgReadyOk returns a tuple with the SupabaseOrgReady field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetSupabaseOrgReadyOk() (*bool, bool) {
	if o == nil || IsNil(o.SupabaseOrgReady) {
		return nil, false
	}
	return o.SupabaseOrgReady, true
}

// HasSupabaseOrgReady returns a boolean if a field has been set.
func (o *FeaturesInfo) HasSupabaseOrgReady() bool {
	if o != nil && !IsNil(o.SupabaseOrgReady) {
		return true
	}

	return false
}

// SetSupabaseOrgReady gets a reference to the given bool and assigns it to the SupabaseOrgReady field.
func (o *FeaturesInfo) SetSupabaseOrgReady(v bool) {
	o.SupabaseOrgReady = &v
}

// GetObservations returns the Observations field value
func (o *FeaturesInfo) GetObservations() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Observations
}

// GetObservationsOk returns a tuple with the Observations field value
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetObservationsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Observations, true
}

// SetObservations sets field value
func (o *FeaturesInfo) SetObservations(v bool) {
	o.Observations = v
}

// GetMcp returns the Mcp field value
func (o *FeaturesInfo) GetMcp() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Mcp
}

// GetMcpOk returns a tuple with the Mcp field value
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetMcpOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mcp, true
}

// SetMcp sets field value
func (o *FeaturesInfo) SetMcp(v bool) {
	o.Mcp = v
}

// GetWorker returns the Worker field value
func (o *FeaturesInfo) GetWorker() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Worker
}

// GetWorkerOk returns a tuple with the Worker field value
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetWorkerOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Worker, true
}

// SetWorker sets field value
func (o *FeaturesInfo) SetWorker(v bool) {
	o.Worker = v
}

// GetBankConfigApi returns the BankConfigApi field value
func (o *FeaturesInfo) GetBankConfigApi() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.BankConfigApi
}

// GetBankConfigApiOk returns a tuple with the BankConfigApi field value
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetBankConfigApiOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankConfigApi, true
}

// SetBankConfigApi sets field value
func (o *FeaturesInfo) SetBankConfigApi(v bool) {
	o.BankConfigApi = v
}

// GetBankLlmHealth returns the BankLlmHealth field value
func (o *FeaturesInfo) GetBankLlmHealth() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.BankLlmHealth
}

// GetBankLlmHealthOk returns a tuple with the BankLlmHealth field value
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetBankLlmHealthOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankLlmHealth, true
}

// SetBankLlmHealth sets field value
func (o *FeaturesInfo) SetBankLlmHealth(v bool) {
	o.BankLlmHealth = v
}

// GetFileUploadApi returns the FileUploadApi field value
func (o *FeaturesInfo) GetFileUploadApi() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FileUploadApi
}

// GetFileUploadApiOk returns a tuple with the FileUploadApi field value
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetFileUploadApiOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileUploadApi, true
}

// SetFileUploadApi sets field value
func (o *FeaturesInfo) SetFileUploadApi(v bool) {
	o.FileUploadApi = v
}

// GetDocumentExportApi returns the DocumentExportApi field value
func (o *FeaturesInfo) GetDocumentExportApi() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DocumentExportApi
}

// GetDocumentExportApiOk returns a tuple with the DocumentExportApi field value
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetDocumentExportApiOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentExportApi, true
}

// SetDocumentExportApi sets field value
func (o *FeaturesInfo) SetDocumentExportApi(v bool) {
	o.DocumentExportApi = v
}

// GetDocumentImportApi returns the DocumentImportApi field value
func (o *FeaturesInfo) GetDocumentImportApi() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DocumentImportApi
}

// GetDocumentImportApiOk returns a tuple with the DocumentImportApi field value
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetDocumentImportApiOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentImportApi, true
}

// SetDocumentImportApi sets field value
func (o *FeaturesInfo) SetDocumentImportApi(v bool) {
	o.DocumentImportApi = v
}

// GetAuditLog returns the AuditLog field value
func (o *FeaturesInfo) GetAuditLog() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AuditLog
}

// GetAuditLogOk returns a tuple with the AuditLog field value
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetAuditLogOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditLog, true
}

// SetAuditLog sets field value
func (o *FeaturesInfo) SetAuditLog(v bool) {
	o.AuditLog = v
}

// GetLlmTrace returns the LlmTrace field value
func (o *FeaturesInfo) GetLlmTrace() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LlmTrace
}

// GetLlmTraceOk returns a tuple with the LlmTrace field value
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetLlmTraceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LlmTrace, true
}

// SetLlmTrace sets field value
func (o *FeaturesInfo) SetLlmTrace(v bool) {
	o.LlmTrace = v
}

// GetStoreDocumentText returns the StoreDocumentText field value
func (o *FeaturesInfo) GetStoreDocumentText() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.StoreDocumentText
}

// GetStoreDocumentTextOk returns a tuple with the StoreDocumentText field value
// and a boolean to check if the value has been set.
func (o *FeaturesInfo) GetStoreDocumentTextOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoreDocumentText, true
}

// SetStoreDocumentText sets field value
func (o *FeaturesInfo) SetStoreDocumentText(v bool) {
	o.StoreDocumentText = v
}

func (o FeaturesInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeaturesInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthzProfile) {
		toSerialize["authz_profile"] = o.AuthzProfile
	}
	if o.TenantExtension.IsSet() {
		toSerialize["tenant_extension"] = o.TenantExtension.Get()
	}
	if o.OperationValidatorExtension.IsSet() {
		toSerialize["operation_validator_extension"] = o.OperationValidatorExtension.Get()
	}
	if !IsNil(o.SupabaseOrgReady) {
		toSerialize["supabase_org_ready"] = o.SupabaseOrgReady
	}
	toSerialize["observations"] = o.Observations
	toSerialize["mcp"] = o.Mcp
	toSerialize["worker"] = o.Worker
	toSerialize["bank_config_api"] = o.BankConfigApi
	toSerialize["bank_llm_health"] = o.BankLlmHealth
	toSerialize["file_upload_api"] = o.FileUploadApi
	toSerialize["document_export_api"] = o.DocumentExportApi
	toSerialize["document_import_api"] = o.DocumentImportApi
	toSerialize["audit_log"] = o.AuditLog
	toSerialize["llm_trace"] = o.LlmTrace
	toSerialize["store_document_text"] = o.StoreDocumentText
	return toSerialize, nil
}

func (o *FeaturesInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"observations",
		"mcp",
		"worker",
		"bank_config_api",
		"bank_llm_health",
		"file_upload_api",
		"document_export_api",
		"document_import_api",
		"audit_log",
		"llm_trace",
		"store_document_text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFeaturesInfo := _FeaturesInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFeaturesInfo)

	if err != nil {
		return err
	}

	*o = FeaturesInfo(varFeaturesInfo)

	return err
}

type NullableFeaturesInfo struct {
	value *FeaturesInfo
	isSet bool
}

func (v NullableFeaturesInfo) Get() *FeaturesInfo {
	return v.value
}

func (v *NullableFeaturesInfo) Set(val *FeaturesInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFeaturesInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFeaturesInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeaturesInfo(val *FeaturesInfo) *NullableFeaturesInfo {
	return &NullableFeaturesInfo{value: val, isSet: true}
}

func (v NullableFeaturesInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeaturesInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


