/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.4.16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the UpdateDocumentTagsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDocumentTagsResponse{}

// UpdateDocumentTagsResponse Response model for update document tags endpoint.
type UpdateDocumentTagsResponse struct {
	Success *bool `json:"success,omitempty"`
}

// NewUpdateDocumentTagsResponse instantiates a new UpdateDocumentTagsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDocumentTagsResponse() *UpdateDocumentTagsResponse {
	this := UpdateDocumentTagsResponse{}
	var success bool = true
	this.Success = &success
	return &this
}

// NewUpdateDocumentTagsResponseWithDefaults instantiates a new UpdateDocumentTagsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDocumentTagsResponseWithDefaults() *UpdateDocumentTagsResponse {
	this := UpdateDocumentTagsResponse{}
	var success bool = true
	this.Success = &success
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UpdateDocumentTagsResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDocumentTagsResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UpdateDocumentTagsResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UpdateDocumentTagsResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o UpdateDocumentTagsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDocumentTagsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableUpdateDocumentTagsResponse struct {
	value *UpdateDocumentTagsResponse
	isSet bool
}

func (v NullableUpdateDocumentTagsResponse) Get() *UpdateDocumentTagsResponse {
	return v.value
}

func (v *NullableUpdateDocumentTagsResponse) Set(val *UpdateDocumentTagsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDocumentTagsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDocumentTagsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDocumentTagsResponse(val *UpdateDocumentTagsResponse) *NullableUpdateDocumentTagsResponse {
	return &NullableUpdateDocumentTagsResponse{value: val, isSet: true}
}

func (v NullableUpdateDocumentTagsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDocumentTagsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


