/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PromptPreviewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptPreviewResponse{}

// PromptPreviewResponse The messages one call of the operation would send.  `messages` is in send order, system first. Both are always present because a mission is not necessarily in the system prompt: retain and observations keep their system prompt bank-agnostic (so one provider-side cache serves every bank) and carry the mission in the user message instead.  When `skipped_reason` is set the configuration means no prompt is sent at all — `chunks` extraction mode stores each chunk verbatim and never calls an LLM — and `messages` is empty.
type PromptPreviewResponse struct {
	// The operation these prompts belong to.
	Operation string `json:"operation"`
	// Request messages, in send order. Each is given as the blocks it is built from.
	Messages []PromptMessageModel `json:"messages,omitempty"`
	ResponseSchema map[string]interface{} `json:"response_schema,omitempty"`
	SkippedReason NullableString `json:"skipped_reason,omitempty"`
}

type _PromptPreviewResponse PromptPreviewResponse

// NewPromptPreviewResponse instantiates a new PromptPreviewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptPreviewResponse(operation string) *PromptPreviewResponse {
	this := PromptPreviewResponse{}
	this.Operation = operation
	return &this
}

// NewPromptPreviewResponseWithDefaults instantiates a new PromptPreviewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptPreviewResponseWithDefaults() *PromptPreviewResponse {
	this := PromptPreviewResponse{}
	return &this
}

// GetOperation returns the Operation field value
func (o *PromptPreviewResponse) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *PromptPreviewResponse) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *PromptPreviewResponse) SetOperation(v string) {
	o.Operation = v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *PromptPreviewResponse) GetMessages() []PromptMessageModel {
	if o == nil || IsNil(o.Messages) {
		var ret []PromptMessageModel
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptPreviewResponse) GetMessagesOk() ([]PromptMessageModel, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *PromptPreviewResponse) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []PromptMessageModel and assigns it to the Messages field.
func (o *PromptPreviewResponse) SetMessages(v []PromptMessageModel) {
	o.Messages = v
}

// GetResponseSchema returns the ResponseSchema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewResponse) GetResponseSchema() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.ResponseSchema
}

// GetResponseSchemaOk returns a tuple with the ResponseSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewResponse) GetResponseSchemaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ResponseSchema) {
		return map[string]interface{}{}, false
	}
	return o.ResponseSchema, true
}

// HasResponseSchema returns a boolean if a field has been set.
func (o *PromptPreviewResponse) HasResponseSchema() bool {
	if o != nil && !IsNil(o.ResponseSchema) {
		return true
	}

	return false
}

// SetResponseSchema gets a reference to the given map[string]interface{} and assigns it to the ResponseSchema field.
func (o *PromptPreviewResponse) SetResponseSchema(v map[string]interface{}) {
	o.ResponseSchema = v
}

// GetSkippedReason returns the SkippedReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptPreviewResponse) GetSkippedReason() string {
	if o == nil || IsNil(o.SkippedReason.Get()) {
		var ret string
		return ret
	}
	return *o.SkippedReason.Get()
}

// GetSkippedReasonOk returns a tuple with the SkippedReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptPreviewResponse) GetSkippedReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SkippedReason.Get(), o.SkippedReason.IsSet()
}

// HasSkippedReason returns a boolean if a field has been set.
func (o *PromptPreviewResponse) HasSkippedReason() bool {
	if o != nil && o.SkippedReason.IsSet() {
		return true
	}

	return false
}

// SetSkippedReason gets a reference to the given NullableString and assigns it to the SkippedReason field.
func (o *PromptPreviewResponse) SetSkippedReason(v string) {
	o.SkippedReason.Set(&v)
}
// SetSkippedReasonNil sets the value for SkippedReason to be an explicit nil
func (o *PromptPreviewResponse) SetSkippedReasonNil() {
	o.SkippedReason.Set(nil)
}

// UnsetSkippedReason ensures that no value is present for SkippedReason, not even an explicit nil
func (o *PromptPreviewResponse) UnsetSkippedReason() {
	o.SkippedReason.Unset()
}

func (o PromptPreviewResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptPreviewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operation"] = o.Operation
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	if o.ResponseSchema != nil {
		toSerialize["response_schema"] = o.ResponseSchema
	}
	if o.SkippedReason.IsSet() {
		toSerialize["skipped_reason"] = o.SkippedReason.Get()
	}
	return toSerialize, nil
}

func (o *PromptPreviewResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPromptPreviewResponse := _PromptPreviewResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPromptPreviewResponse)

	if err != nil {
		return err
	}

	*o = PromptPreviewResponse(varPromptPreviewResponse)

	return err
}

type NullablePromptPreviewResponse struct {
	value *PromptPreviewResponse
	isSet bool
}

func (v NullablePromptPreviewResponse) Get() *PromptPreviewResponse {
	return v.value
}

func (v *NullablePromptPreviewResponse) Set(val *PromptPreviewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptPreviewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptPreviewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptPreviewResponse(val *PromptPreviewResponse) *NullablePromptPreviewResponse {
	return &NullablePromptPreviewResponse{value: val, isSet: true}
}

func (v NullablePromptPreviewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptPreviewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


