/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the ConsolidationEventData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsolidationEventData{}

// ConsolidationEventData struct for ConsolidationEventData
type ConsolidationEventData struct {
	ObservationsCreated *int32 `json:"observations_created,omitempty"`
	ObservationsUpdated *int32 `json:"observations_updated,omitempty"`
	ObservationsDeleted *int32 `json:"observations_deleted,omitempty"`
	ErrorMessage *string `json:"error_message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConsolidationEventData ConsolidationEventData

// NewConsolidationEventData instantiates a new ConsolidationEventData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsolidationEventData() *ConsolidationEventData {
	this := ConsolidationEventData{}
	return &this
}

// NewConsolidationEventDataWithDefaults instantiates a new ConsolidationEventData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsolidationEventDataWithDefaults() *ConsolidationEventData {
	this := ConsolidationEventData{}
	return &this
}

// GetObservationsCreated returns the ObservationsCreated field value if set, zero value otherwise.
func (o *ConsolidationEventData) GetObservationsCreated() int32 {
	if o == nil || IsNil(o.ObservationsCreated) {
		var ret int32
		return ret
	}
	return *o.ObservationsCreated
}

// GetObservationsCreatedOk returns a tuple with the ObservationsCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsolidationEventData) GetObservationsCreatedOk() (*int32, bool) {
	if o == nil || IsNil(o.ObservationsCreated) {
		return nil, false
	}
	return o.ObservationsCreated, true
}

// HasObservationsCreated returns a boolean if a field has been set.
func (o *ConsolidationEventData) HasObservationsCreated() bool {
	if o != nil && !IsNil(o.ObservationsCreated) {
		return true
	}

	return false
}

// SetObservationsCreated gets a reference to the given int32 and assigns it to the ObservationsCreated field.
func (o *ConsolidationEventData) SetObservationsCreated(v int32) {
	o.ObservationsCreated = &v
}

// GetObservationsUpdated returns the ObservationsUpdated field value if set, zero value otherwise.
func (o *ConsolidationEventData) GetObservationsUpdated() int32 {
	if o == nil || IsNil(o.ObservationsUpdated) {
		var ret int32
		return ret
	}
	return *o.ObservationsUpdated
}

// GetObservationsUpdatedOk returns a tuple with the ObservationsUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsolidationEventData) GetObservationsUpdatedOk() (*int32, bool) {
	if o == nil || IsNil(o.ObservationsUpdated) {
		return nil, false
	}
	return o.ObservationsUpdated, true
}

// HasObservationsUpdated returns a boolean if a field has been set.
func (o *ConsolidationEventData) HasObservationsUpdated() bool {
	if o != nil && !IsNil(o.ObservationsUpdated) {
		return true
	}

	return false
}

// SetObservationsUpdated gets a reference to the given int32 and assigns it to the ObservationsUpdated field.
func (o *ConsolidationEventData) SetObservationsUpdated(v int32) {
	o.ObservationsUpdated = &v
}

// GetObservationsDeleted returns the ObservationsDeleted field value if set, zero value otherwise.
func (o *ConsolidationEventData) GetObservationsDeleted() int32 {
	if o == nil || IsNil(o.ObservationsDeleted) {
		var ret int32
		return ret
	}
	return *o.ObservationsDeleted
}

// GetObservationsDeletedOk returns a tuple with the ObservationsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsolidationEventData) GetObservationsDeletedOk() (*int32, bool) {
	if o == nil || IsNil(o.ObservationsDeleted) {
		return nil, false
	}
	return o.ObservationsDeleted, true
}

// HasObservationsDeleted returns a boolean if a field has been set.
func (o *ConsolidationEventData) HasObservationsDeleted() bool {
	if o != nil && !IsNil(o.ObservationsDeleted) {
		return true
	}

	return false
}

// SetObservationsDeleted gets a reference to the given int32 and assigns it to the ObservationsDeleted field.
func (o *ConsolidationEventData) SetObservationsDeleted(v int32) {
	o.ObservationsDeleted = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *ConsolidationEventData) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsolidationEventData) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ConsolidationEventData) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *ConsolidationEventData) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

func (o ConsolidationEventData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsolidationEventData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObservationsCreated) {
		toSerialize["observations_created"] = o.ObservationsCreated
	}
	if !IsNil(o.ObservationsUpdated) {
		toSerialize["observations_updated"] = o.ObservationsUpdated
	}
	if !IsNil(o.ObservationsDeleted) {
		toSerialize["observations_deleted"] = o.ObservationsDeleted
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["error_message"] = o.ErrorMessage
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConsolidationEventData) UnmarshalJSON(data []byte) (err error) {
	varConsolidationEventData := _ConsolidationEventData{}

	err = json.Unmarshal(data, &varConsolidationEventData)

	if err != nil {
		return err
	}

	*o = ConsolidationEventData(varConsolidationEventData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "observations_created")
		delete(additionalProperties, "observations_updated")
		delete(additionalProperties, "observations_deleted")
		delete(additionalProperties, "error_message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConsolidationEventData struct {
	value *ConsolidationEventData
	isSet bool
}

func (v NullableConsolidationEventData) Get() *ConsolidationEventData {
	return v.value
}

func (v *NullableConsolidationEventData) Set(val *ConsolidationEventData) {
	v.value = val
	v.isSet = true
}

func (v NullableConsolidationEventData) IsSet() bool {
	return v.isSet
}

func (v *NullableConsolidationEventData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsolidationEventData(val *ConsolidationEventData) *NullableConsolidationEventData {
	return &NullableConsolidationEventData{value: val, isSet: true}
}

func (v NullableConsolidationEventData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsolidationEventData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


