/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServerLlmConfigResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerLlmConfigResponse{}

// ServerLlmConfigResponse The instance-level LLM configuration. The API key is never returned — only whether one is set.
type ServerLlmConfigResponse struct {
	// Configured LLM provider id.
	Provider string `json:"provider"`
	Model NullableString `json:"model,omitempty"`
	BaseUrl NullableString `json:"base_url,omitempty"`
	// Whether an API key is stored (the key itself is never returned).
	ApiKeyIsSet bool `json:"api_key_is_set"`
	// Whether the instance can perform LLM operations (provider set, and a key is present for providers that require one).
	IsConfigured bool `json:"is_configured"`
}

type _ServerLlmConfigResponse ServerLlmConfigResponse

// NewServerLlmConfigResponse instantiates a new ServerLlmConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerLlmConfigResponse(provider string, apiKeyIsSet bool, isConfigured bool) *ServerLlmConfigResponse {
	this := ServerLlmConfigResponse{}
	this.Provider = provider
	this.ApiKeyIsSet = apiKeyIsSet
	this.IsConfigured = isConfigured
	return &this
}

// NewServerLlmConfigResponseWithDefaults instantiates a new ServerLlmConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerLlmConfigResponseWithDefaults() *ServerLlmConfigResponse {
	this := ServerLlmConfigResponse{}
	return &this
}

// GetProvider returns the Provider field value
func (o *ServerLlmConfigResponse) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *ServerLlmConfigResponse) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *ServerLlmConfigResponse) SetProvider(v string) {
	o.Provider = v
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServerLlmConfigResponse) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServerLlmConfigResponse) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *ServerLlmConfigResponse) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *ServerLlmConfigResponse) SetModel(v string) {
	o.Model.Set(&v)
}
// SetModelNil sets the value for Model to be an explicit nil
func (o *ServerLlmConfigResponse) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *ServerLlmConfigResponse) UnsetModel() {
	o.Model.Unset()
}

// GetBaseUrl returns the BaseUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServerLlmConfigResponse) GetBaseUrl() string {
	if o == nil || IsNil(o.BaseUrl.Get()) {
		var ret string
		return ret
	}
	return *o.BaseUrl.Get()
}

// GetBaseUrlOk returns a tuple with the BaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServerLlmConfigResponse) GetBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseUrl.Get(), o.BaseUrl.IsSet()
}

// HasBaseUrl returns a boolean if a field has been set.
func (o *ServerLlmConfigResponse) HasBaseUrl() bool {
	if o != nil && o.BaseUrl.IsSet() {
		return true
	}

	return false
}

// SetBaseUrl gets a reference to the given NullableString and assigns it to the BaseUrl field.
func (o *ServerLlmConfigResponse) SetBaseUrl(v string) {
	o.BaseUrl.Set(&v)
}
// SetBaseUrlNil sets the value for BaseUrl to be an explicit nil
func (o *ServerLlmConfigResponse) SetBaseUrlNil() {
	o.BaseUrl.Set(nil)
}

// UnsetBaseUrl ensures that no value is present for BaseUrl, not even an explicit nil
func (o *ServerLlmConfigResponse) UnsetBaseUrl() {
	o.BaseUrl.Unset()
}

// GetApiKeyIsSet returns the ApiKeyIsSet field value
func (o *ServerLlmConfigResponse) GetApiKeyIsSet() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ApiKeyIsSet
}

// GetApiKeyIsSetOk returns a tuple with the ApiKeyIsSet field value
// and a boolean to check if the value has been set.
func (o *ServerLlmConfigResponse) GetApiKeyIsSetOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKeyIsSet, true
}

// SetApiKeyIsSet sets field value
func (o *ServerLlmConfigResponse) SetApiKeyIsSet(v bool) {
	o.ApiKeyIsSet = v
}

// GetIsConfigured returns the IsConfigured field value
func (o *ServerLlmConfigResponse) GetIsConfigured() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsConfigured
}

// GetIsConfiguredOk returns a tuple with the IsConfigured field value
// and a boolean to check if the value has been set.
func (o *ServerLlmConfigResponse) GetIsConfiguredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsConfigured, true
}

// SetIsConfigured sets field value
func (o *ServerLlmConfigResponse) SetIsConfigured(v bool) {
	o.IsConfigured = v
}

func (o ServerLlmConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerLlmConfigResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.BaseUrl.IsSet() {
		toSerialize["base_url"] = o.BaseUrl.Get()
	}
	toSerialize["api_key_is_set"] = o.ApiKeyIsSet
	toSerialize["is_configured"] = o.IsConfigured
	return toSerialize, nil
}

func (o *ServerLlmConfigResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"api_key_is_set",
		"is_configured",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServerLlmConfigResponse := _ServerLlmConfigResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServerLlmConfigResponse)

	if err != nil {
		return err
	}

	*o = ServerLlmConfigResponse(varServerLlmConfigResponse)

	return err
}

type NullableServerLlmConfigResponse struct {
	value *ServerLlmConfigResponse
	isSet bool
}

func (v NullableServerLlmConfigResponse) Get() *ServerLlmConfigResponse {
	return v.value
}

func (v *NullableServerLlmConfigResponse) Set(val *ServerLlmConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServerLlmConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServerLlmConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerLlmConfigResponse(val *ServerLlmConfigResponse) *NullableServerLlmConfigResponse {
	return &NullableServerLlmConfigResponse{value: val, isSet: true}
}

func (v NullableServerLlmConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerLlmConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


