/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServerLlmHealthResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerLlmHealthResponse{}

// ServerLlmHealthResponse Instance-level LLM connectivity probe across retain/consolidation/reflect. Discloses status only — never the provider, model, endpoint, API key, or raw error.
type ServerLlmHealthResponse struct {
	// Connectivity status per operation (retain, consolidation, reflect)
	Operations []LlmOperationHealth `json:"operations"`
}

type _ServerLlmHealthResponse ServerLlmHealthResponse

// NewServerLlmHealthResponse instantiates a new ServerLlmHealthResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerLlmHealthResponse(operations []LlmOperationHealth) *ServerLlmHealthResponse {
	this := ServerLlmHealthResponse{}
	this.Operations = operations
	return &this
}

// NewServerLlmHealthResponseWithDefaults instantiates a new ServerLlmHealthResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerLlmHealthResponseWithDefaults() *ServerLlmHealthResponse {
	this := ServerLlmHealthResponse{}
	return &this
}

// GetOperations returns the Operations field value
func (o *ServerLlmHealthResponse) GetOperations() []LlmOperationHealth {
	if o == nil {
		var ret []LlmOperationHealth
		return ret
	}

	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value
// and a boolean to check if the value has been set.
func (o *ServerLlmHealthResponse) GetOperationsOk() ([]LlmOperationHealth, bool) {
	if o == nil {
		return nil, false
	}
	return o.Operations, true
}

// SetOperations sets field value
func (o *ServerLlmHealthResponse) SetOperations(v []LlmOperationHealth) {
	o.Operations = v
}

func (o ServerLlmHealthResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerLlmHealthResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operations"] = o.Operations
	return toSerialize, nil
}

func (o *ServerLlmHealthResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServerLlmHealthResponse := _ServerLlmHealthResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServerLlmHealthResponse)

	if err != nil {
		return err
	}

	*o = ServerLlmHealthResponse(varServerLlmHealthResponse)

	return err
}

type NullableServerLlmHealthResponse struct {
	value *ServerLlmHealthResponse
	isSet bool
}

func (v NullableServerLlmHealthResponse) Get() *ServerLlmHealthResponse {
	return v.value
}

func (v *NullableServerLlmHealthResponse) Set(val *ServerLlmHealthResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServerLlmHealthResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServerLlmHealthResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerLlmHealthResponse(val *ServerLlmHealthResponse) *NullableServerLlmHealthResponse {
	return &NullableServerLlmHealthResponse{value: val, isSet: true}
}

func (v NullableServerLlmHealthResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerLlmHealthResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


